# Preliminary Exploratory Data Analysis (Pre-EDA)

In the upcoming Preliminary Exploratory Data Analysis (Pre-EDA), we will conduct a brief examination of the available data. This process is carried out after having done a concise extract, transform and load (ETL) process to improve data quality.
In this Pre-EDA we are going to focus on analyzing the quality of the data provided by the client in order to evaluate the way in which the data will be treated during the development of the project.

In [1]:
# Always Run this code

import builtin.utils as ut

StatementMeta(, 6ded00d1-9621-4717-bd4e-619d370d69cb, 3, Finished, Available)

## 1 Memory Usage Calculation

Our main objective is to make a comparisson between the amount of Gbs used into the original file and the new amount for those files in a .parquet format.

This will show us how efficent our database can be by reducing his mass.

In [2]:
estados_size = round(ut.calculate_original_memory_usage('/lakehouse/default/Files/original/reviews-estados'), 2)
sitios_size = round(ut.calculate_original_memory_usage('/lakehouse/default/Files/original/metadata-sitios'), 2)
yelp_size = round(ut.calculate_original_memory_usage('/lakehouse/default/Files/original/Yelp'), 2)

total_size = estados_size + sitios_size + yelp_size
print(f'Total size of original data: \nEstados: {estados_size}Mb\n Sitios: {sitios_size}Mb\n Yelp: {yelp_size}Mb\n Total size: {total_size}Mb\n')

parquet_size = ut.calculate_parquet_memory_usage('/lakehouse/default/Files/df_database')
print(f'Total size of compressed data: {round(parquet_size,2)}Mb\n')

diff_size = total_size - parquet_size
print(f'Savings in resource and size usage: {round(diff_size,2)}Mb\n')

size_perc = (diff_size/total_size)*100
print(f'Percentage savings in resources: {round(size_perc,2)}%\n')

StatementMeta(, 6ded00d1-9621-4717-bd4e-619d370d69cb, 4, Finished, Available)

Total size of original data:
Estados: 24917.16Mb
 Sitios: 2832.32Mb
 Yelp: 8465.34Mb
 Total size: 36214.82Mb

Total size of compressed data: 10897.09Mb

Savings in resource and size usage: 25317.73Mb

Percentage savings in resources: 69.91%

## 2. Data Quality

In order to review the quality of the data, to know how we can approach our work, we carry out an inspection of each file, reviewing the data contained in each column of the tables to be studied.

### 2.1 Data quality of files in the 'Metadata_sites_parquet' folder

In [3]:
folder_path = '/lakehouse/default/Files/df_database/Metadata_sitios_parquet/'

# Apply the apply_data_summ_to_parquet_folder function to get the summaries
summaries = ut.data_summ_on_parquet(folder_path)

StatementMeta(, 6ded00d1-9621-4717-bd4e-619d370d69cb, 5, Finished, Available)

metadata-sitios Summary

Total rows:  275001

Total full null rows:  0
          Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
            name           [<class 'str'>, <class 'NoneType'>]       274998      0.00            3
         address           [<class 'str'>, <class 'NoneType'>]       269428      2.03         5573
         gmap_id                               [<class 'str'>]       275001      0.00            0
     description           [<class 'NoneType'>, <class 'str'>]        27900     89.85       247101
        latitude                             [<class 'float'>]       275001      0.00            0
       longitude                             [<class 'float'>]       275001      0.00            0
        category [<class 'numpy.ndarray'>, <class 'NoneType'>]       273662      0.49         1339
      avg_rating                             [<class 'float'>]       275001      0.00            0
  num_of_reviews                               [<class 'int'>]       275001      0.00            0
           price           [<class 'NoneType'>, <class 'str'>]        31139     88.68       243862
           hours [<class 'numpy.ndarray'>, <class 'NoneType'>]       210287     23.53        64714
            MISC          [<class 'dict'>, <class 'NoneType'>]       221703     19.38        53298
           state           [<class 'str'>, <class 'NoneType'>]       212960     22.56        62041
relative_results [<class 'numpy.ndarray'>, <class 'NoneType'>]       254406      7.49        20595
             url                               [<class 'str'>]       275001      0.00            0
=====================================

### 2.2 Data quality of files in the 'Review_estados_parquet' folder

In [4]:
folder_path = '/lakehouse/default/Files/df_database/Review_estados_parquet/'

# Apply the apply_data_summ_to_parquet_folder function to get the summaries
summaries = ut.data_summ_on_parquet(folder_path)

StatementMeta(, 6ded00d1-9621-4717-bd4e-619d370d69cb, 6, Finished, Available)

Alabama Summary

Total rows:  1800000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      1800000      0.00            0
   name                               [<class 'str'>]      1800000      0.00            0
   time                               [<class 'int'>]      1800000      0.00            0
 rating                               [<class 'int'>]      1800000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]       966601     46.30       833399
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        36170     97.99      1763830
   resp          [<class 'NoneType'>, <class 'dict'>]       207283     88.48      1592717
gmap_id                               [<class 'str'>]      1800000      0.00            0
   date                               [<class 'str'>]      1800000      0.00            0
=====================================
Alaska Summary

Total rows:  521515

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]       521515      0.00            0
   name                               [<class 'str'>]       521515      0.00            0
   time                               [<class 'int'>]       521515      0.00            0
 rating                               [<class 'int'>]       521515      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]       298257     42.81       223258
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        20851     96.00       500664
   resp          [<class 'NoneType'>, <class 'dict'>]        44232     91.52       477283
gmap_id                               [<class 'str'>]       521515      0.00            0
   date                               [<class 'str'>]       521515      0.00            0
=====================================
Arizona Summary

Total rows:  2100000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      2100000      0.00            0
   name                               [<class 'str'>]      2100000      0.00            0
   time                               [<class 'int'>]      2100000      0.00            0
 rating                               [<class 'int'>]      2100000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1267816     39.63       832184
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        63871     96.96      2036129
   resp          [<class 'NoneType'>, <class 'dict'>]       339149     83.85      1760851
gmap_id                               [<class 'str'>]      2100000      0.00            0
   date                               [<class 'str'>]      2100000      0.00            0
=====================================
Arkansas Summary

Total rows:  2400000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      2400000      0.00            0
   name                               [<class 'str'>]      2400000      0.00            0
   time                               [<class 'int'>]      2400000      0.00            0
 rating                               [<class 'int'>]      2400000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1295752     46.01      1104248
   pics [<class 'numpy.ndarray'>, <class 'NoneType'>]        48258     97.99      2351742
   resp          [<class 'dict'>, <class 'NoneType'>]       254783     89.38      2145217
gmap_id                               [<class 'str'>]      2400000      0.00            0
   date                               [<class 'str'>]      2400000      0.00            0
=====================================
California Summary

Total rows:  2700000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      2700000      0.00            0
   name                               [<class 'str'>]      2700000      0.00            0
   time                               [<class 'int'>]      2700000      0.00            0
 rating                               [<class 'int'>]      2700000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1529036     43.37      1170964
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        99290     96.32      2600710
   resp          [<class 'NoneType'>, <class 'dict'>]       245169     90.92      2454831
gmap_id                               [<class 'str'>]      2700000      0.00            0
   date                               [<class 'str'>]      2700000      0.00            0
=====================================
Colorado Summary

Total rows:  2400000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      2400000      0.00            0
   name                               [<class 'str'>]      2400000      0.00            0
   time                               [<class 'int'>]      2400000      0.00            0
 rating                               [<class 'int'>]      2400000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1479563     38.35       920437
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        76472     96.81      2323528
   resp          [<class 'NoneType'>, <class 'dict'>]       412135     82.83      1987865
gmap_id                               [<class 'str'>]      2400000      0.00            0
   date                               [<class 'str'>]      2400000      0.00            0
=====================================
Connecticut Summary

Total rows:  2680107

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      2680107      0.00            0
   name                               [<class 'str'>]      2680107      0.00            0
   time                               [<class 'int'>]      2680107      0.00            0
 rating                               [<class 'int'>]      2680107      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1417301     47.12      1262806
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        70782     97.36      2609325
   resp          [<class 'NoneType'>, <class 'dict'>]       260321     90.29      2419786
gmap_id                               [<class 'str'>]      2680107      0.00            0
   date                               [<class 'str'>]      2680107      0.00            0
=====================================
Delaware Summary

Total rows:  905537

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]       905537      0.00            0
   name                               [<class 'str'>]       905537      0.00            0
   time                               [<class 'int'>]       905537      0.00            0
 rating                               [<class 'int'>]       905537      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]       497198     45.09       408339
   pics [<class 'numpy.ndarray'>, <class 'NoneType'>]        19031     97.90       886506
   resp          [<class 'NoneType'>, <class 'dict'>]        98075     89.17       807462
gmap_id                               [<class 'str'>]       905537      0.00            0
   date                               [<class 'str'>]       905537      0.00            0
=====================================
District_of_Columbia Summary

Total rows:  564783

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]       564783      0.00            0
   name                               [<class 'str'>]       564783      0.00            0
   time                               [<class 'int'>]       564783      0.00            0
 rating                               [<class 'int'>]       564783      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]       294462     47.86       270321
   pics [<class 'numpy.ndarray'>, <class 'NoneType'>]        29355     94.80       535428
   resp          [<class 'NoneType'>, <class 'dict'>]        41682     92.62       523101
gmap_id                               [<class 'str'>]       564783      0.00            0
   date                               [<class 'str'>]       564783      0.00            0
=====================================
Florida Summary

Total rows:  2850000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      2850000      0.00            0
   name                               [<class 'str'>]      2850000      0.00            0
   time                               [<class 'int'>]      2850000      0.00            0
 rating                               [<class 'int'>]      2850000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1770490     37.88      1079510
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]       104190     96.34      2745810
   resp          [<class 'dict'>, <class 'NoneType'>]       455399     84.02      2394601
gmap_id                               [<class 'str'>]      2850000      0.00            0
   date                               [<class 'str'>]      2850000      0.00            0
=====================================
Georgia Summary

Total rows:  1950000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      1950000      0.00            0
   name                               [<class 'str'>]      1950000      0.00            0
   time                               [<class 'int'>]      1950000      0.00            0
 rating                               [<class 'int'>]      1950000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1149497     41.05       800503
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        52839     97.29      1897161
   resp          [<class 'NoneType'>, <class 'dict'>]       289042     85.18      1660958
gmap_id                               [<class 'str'>]      1950000      0.00            0
   date                               [<class 'str'>]      1950000      0.00            0
=====================================
Hawaii Summary

Total rows:  1504347

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      1504347      0.00            0
   name                               [<class 'str'>]      1504347      0.00            0
   time                               [<class 'int'>]      1504347      0.00            0
 rating                               [<class 'int'>]      1504347      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]       852596     43.32       651751
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]       132702     91.18      1371645
   resp          [<class 'NoneType'>, <class 'dict'>]       108799     92.77      1395548
gmap_id                               [<class 'str'>]      1504347      0.00            0
   date                               [<class 'str'>]      1504347      0.00            0
=====================================
Idaho Summary

Total rows:  2085487

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      2085487      0.00            0
   name                               [<class 'str'>]      2085487      0.00            0
   time                               [<class 'int'>]      2085487      0.00            0
 rating                               [<class 'int'>]      2085487      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1189843     42.95       895644
   pics [<class 'numpy.ndarray'>, <class 'NoneType'>]        50182     97.59      2035305
   resp          [<class 'NoneType'>, <class 'dict'>]       293130     85.94      1792357
gmap_id                               [<class 'str'>]      2085487      0.00            0
   date                               [<class 'str'>]      2085487      0.00            0
=====================================
Illinois Summary

Total rows:  2100000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      2100000      0.00            0
   name                               [<class 'str'>]      2100000      0.00            0
   time                               [<class 'int'>]      2100000      0.00            0
 rating                               [<class 'int'>]      2100000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1187782     43.44       912218
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        58374     97.22      2041626
   resp          [<class 'NoneType'>, <class 'dict'>]       255119     87.85      1844881
gmap_id                               [<class 'str'>]      2100000      0.00            0
   date                               [<class 'str'>]      2100000      0.00            0
=====================================
Indiana Summary

Total rows:  2250000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      2250000      0.00            0
   name                               [<class 'str'>]      2250000      0.00            0
   time                               [<class 'int'>]      2250000      0.00            0
 rating                               [<class 'int'>]      2250000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1240490     44.87      1009510
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        47274     97.90      2202726
   resp          [<class 'dict'>, <class 'NoneType'>]       278942     87.60      1971058
gmap_id                               [<class 'str'>]      2250000      0.00            0
   date                               [<class 'str'>]      2250000      0.00            0
=====================================
Iowa Summary

Total rows:  2677684

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      2677684      0.00            0
   name                               [<class 'str'>]      2677684      0.00            0
   time                               [<class 'int'>]      2677684      0.00            0
 rating                               [<class 'int'>]      2677684      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1382508     48.37      1295176
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        48150     98.20      2629534
   resp          [<class 'dict'>, <class 'NoneType'>]       268742     89.96      2408942
gmap_id                               [<class 'str'>]      2677684      0.00            0
   date                               [<class 'str'>]      2677684      0.00            0
=====================================
Kansas Summary

Total rows:  1950000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      1950000      0.00            0
   name                               [<class 'str'>]      1950000      0.00            0
   time                               [<class 'int'>]      1950000      0.00            0
 rating                               [<class 'int'>]      1950000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]      1049396     46.18       900604
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        38154     98.04      1911846
   resp          [<class 'NoneType'>, <class 'dict'>]       233500     88.03      1716500
gmap_id                               [<class 'str'>]      1950000      0.00            0
   date                               [<class 'str'>]      1950000      0.00            0
=====================================
Kentucky Summary

Total rows:  1650000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      1650000      0.00            0
   name                               [<class 'str'>]      1650000      0.00            0
   time                               [<class 'int'>]      1650000      0.00            0
 rating                               [<class 'int'>]      1650000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]       893180     45.87       756820
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        32564     98.03      1617436
   resp          [<class 'NoneType'>, <class 'dict'>]       194501     88.21      1455499
gmap_id                               [<class 'str'>]      1650000      0.00            0
   date                               [<class 'str'>]      1650000      0.00            0
=====================================
Louisiana Summary

Total rows:  1500000

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      1500000      0.00            0
   name                               [<class 'str'>]      1500000      0.00            0
   time                               [<class 'int'>]      1500000      0.00            0
 rating                               [<class 'int'>]      1500000      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]       789116     47.39       710884
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        35628     97.62      1464372
   resp          [<class 'dict'>, <class 'NoneType'>]       160140     89.32      1339860
gmap_id                               [<class 'str'>]      1500000      0.00            0
   date                               [<class 'str'>]      1500000      0.00            0
=====================================
Maine Summary

Total rows:  1123881

Total full null rows:  0
 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]      1123881      0.00            0
   name                               [<class 'str'>]      1123881      0.00            0
   time                               [<class 'int'>]      1123881      0.00            0
 rating                               [<class 'int'>]      1123881      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]       614200     45.35       509681
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]        32185     97.14      1091696
   resp          [<class 'NoneType'>, <class 'dict'>]        95831     91.47      1028050
gmap_id                               [<class 'str'>]      1123881      0.00            0

### 2.3 Data quality of files in the 'Yelp_parquet' folder

In [5]:
folder_path = '/lakehouse/default/Files/df_database/Yelp_parquet/'

# Apply the apply_data_summ_to_parquet_folder function to get the summaries
summaries = ut.data_summ_on_parquet(folder_path)

StatementMeta(, 6ded00d1-9621-4717-bd4e-619d370d69cb, 7, Finished, Available)

business.pkl Summary

Total rows:  150346

Total full null rows:  0
      Column                            Data_type  No_miss_Qty  %Missing  Missing_Qty
 business_id                      [<class 'str'>]       150346      0.00            0
        name                      [<class 'str'>]       150346      0.00            0
     address                      [<class 'str'>]       150346      0.00            0
        city                      [<class 'str'>]       150346      0.00            0
       state  [<class 'NoneType'>, <class 'str'>]       150343      0.00            3
 postal_code                      [<class 'str'>]       150346      0.00            0
    latitude                    [<class 'float'>]       150346      0.00            0
   longitude                    [<class 'float'>]       150346      0.00            0
       stars                    [<class 'float'>]       150346      0.00            0
review_count                      [<class 'int'>]       150346      0.00            0
     is_open                      [<class 'int'>]       150346      0.00            0
  attributes [<class 'dict'>, <class 'NoneType'>]       136602      9.14        13744
  categories  [<class 'str'>, <class 'NoneType'>]       150243      0.07          103
       hours [<class 'NoneType'>, <class 'dict'>]       127123     15.45        23223
=====================================
checkin.json Summary

Total rows:  131930

Total full null rows:  0
     Column       Data_type  No_miss_Qty  %Missing  Missing_Qty
business_id [<class 'str'>]       131930       0.0            0
       date [<class 'str'>]       131930       0.0            0
=====================================
review.json Summary

Total rows:  6990280

Total full null rows:  0
     Column                                            Data_type  No_miss_Qty  %Missing  Missing_Qty
  review_id                                      [<class 'str'>]      6990280       0.0            0
    user_id                                      [<class 'str'>]      6990280       0.0            0
business_id                                      [<class 'str'>]      6990280       0.0            0
      stars                                      [<class 'int'>]      6990280       0.0            0
     useful                                      [<class 'int'>]      6990280       0.0            0
      funny                                      [<class 'int'>]      6990280       0.0            0
       cool                                      [<class 'int'>]      6990280       0.0            0
       text                                      [<class 'str'>]      6990280       0.0            0
       date [<class 'pandas._libs.tslibs.timestamps.Timestamp'>]      6990280       0.0            0
=====================================
tip.json Summary

Total rows:  908915

Total full null rows:  0
          Column                                            Data_type  No_miss_Qty  %Missing  Missing_Qty
         user_id                                      [<class 'str'>]       908915       0.0            0
     business_id                                      [<class 'str'>]       908915       0.0            0
            text                                      [<class 'str'>]       908915       0.0            0
            date [<class 'pandas._libs.tslibs.timestamps.Timestamp'>]       908915       0.0            0
compliment_count                                      [<class 'int'>]       908915       0.0            0
=====================================
user Summary

Total rows:  908915

Total full null rows:  0
          Column                                            Data_type  No_miss_Qty  %Missing  Missing_Qty
         user_id                                      [<class 'str'>]       908915       0.0            0
     business_id                                      [<class 'str'>]       908915       0.0            0
            text                                      [<class 'str'>]       908915       0.0            0
            date [<class 'pandas._libs.tslibs.timestamps.Timestamp'>]       908915       0.0            0
compliment_count                                      [<class 'int'>]       908915       0.0            0
=====================================