# ETL for Google Maps data Files 

We will perform the extraction, transformation and data loading of the data included in the files provided in the Google Maps folder

In [1]:
import io
import os
import pandas as pd
import builtin.utils as ut

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 3, Finished, Available)

___
## 1. Extract data

We going to extract the data from our Data Lake and in a first step, we going to concatenate all data in States folder and the merge with data in Metadata folder.

We create two variables (gm_path, metadata_sites) to store the paths of the Reviews and Metadata folders, data provided by Google Maps.

In [2]:
gm_path = '/lakehouse/default/Files/df_database/Review_estados_parquet'
metadata_sites = '/lakehouse/default/Files/df_database/Metadata_sitios_parquet/metadata-sitios.parquet'
keywords = ['museum', 'park', 'Hotel', 'Motel', 'Hostel', 'restaurant', 'Restaurant', 'forest', 'gallery', 'mall', 'pub', 'Zoo', 'roller coaster']

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 4, Finished, Available)

In [3]:
# Extracting Data
gm_df = ut.clean_states_and_concat(gm_path)
sites_df = ut.clean_sites(metadata_sites, keywords)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 5, Finished, Available)

## 1.1 Dropping unnecesary columns and duplicates

### States Dropping

In [4]:
ut.data_summ(gm_df)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 6, Finished, Available)

 Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
user_id                             [<class 'float'>]     89946359      0.00            0
   name                               [<class 'str'>]     89946359      0.00            0
   time                               [<class 'int'>]     89946359      0.00            0
 rating                               [<class 'int'>]     89946359      0.00            0
   text           [<class 'str'>, <class 'NoneType'>]     50638615     43.70     39307744
   pics [<class 'NoneType'>, <class 'numpy.ndarray'>]      2495679     97.23     87450680
   resp          [<class 'NoneType'>, <class 'dict'>]     11029110     87.74     78917249
gmap_id                               [<class 'str'>]     89946359      0.00            0
   date                               [<class 'str'>]     89946359      0.00            0
  state                               [<class 'str'>]     89946359      0.00            0
=====================================

,Column,Data_type,No_miss_Qty,%Missing,Missing_Qty
0,user_id,[<class 'float'>],89946359,0.00,0
1,name,[<class 'str'>],89946359,0.00,0
2,time,[<class 'int'>],89946359,0.00,0
3,rating,[<class 'int'>],89946359,0.00,0
4,text,"[<class 'str'>, <class 'NoneType'>]",50638615,43.70,39307744
5,pics,"[<class 'NoneType'>, <class 'numpy.ndarray'>]",2495679,97.23,87450680
6,resp,"[<class 'NoneType'>, <class 'dict'>]",11029110,87.74,78917249
7,gmap_id,[<class 'str'>],89946359,0.00,0
8,date,[<class 'str'>],89946359,0.00,0
9,state,[<class 'str'>],89946359,0.00,0

In [5]:
drop_col=['resp', 'pics', 'time']
gm_df.drop(columns=drop_col, inplace=True)
gm_df.drop_duplicates(inplace=True)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 7, Finished, Available)

In [6]:
unique_states = gm_df['state'].unique()
unique_states_list = list(unique_states)
print(unique_states_list)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 8, Finished, Available)

['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District_of_Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New_Hampshire', 'New_Jersey', 'New_Mexico', 'New_York', 'North_Carolina', 'North_Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode_Island', 'South_Carolina', 'South_Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West_Virginia', 'Wisconsin', 'Wyoming']

We going to select the most cultural and turistic states in the USA

In [7]:
# Lista de estados permitidos
allowed_states = ['California', 'Florida', 'New_York', 'Nevada', 'Indiana', 
                  'Massachusetts', 'Illinois', 'District_of_Columbia', 'Louisiana', 'Hawaii, ''South_Carolina']

# Filtrar el DataFrame
gm_df = gm_df[gm_df['state'].isin(allowed_states)]

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 9, Finished, Available)

### Sites Dropping

In [8]:
ut.data_summ(sites_df)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 10, Finished, Available)

          Column                                     Data_type  No_miss_Qty  %Missing  Missing_Qty
            name                               [<class 'str'>]       277783      0.00            0
         address           [<class 'str'>, <class 'NoneType'>]       275798      0.71         1985
         gmap_id                               [<class 'str'>]       277783      0.00            0
     description           [<class 'NoneType'>, <class 'str'>]        80137     71.15       197646
        latitude                             [<class 'float'>]       277783      0.00            0
       longitude                             [<class 'float'>]       277783      0.00            0
        category                     [<class 'numpy.ndarray'>]       277783      0.00            0
      avg_rating                             [<class 'float'>]       277783      0.00            0
  num_of_reviews                               [<class 'int'>]       277783      0.00            0
           price           [<class 'NoneType'>, <class 'str'>]       101239     63.55       176544
           hours [<class 'numpy.ndarray'>, <class 'NoneType'>]       222694     19.83        55089
            MISC          [<class 'dict'>, <class 'NoneType'>]       255936      7.86        21847
           state           [<class 'str'>, <class 'NoneType'>]       225054     18.98        52729
relative_results [<class 'numpy.ndarray'>, <class 'NoneType'>]       229507     17.38        48276
             url                               [<class 'str'>]       277783      0.00            0
=====================================

,Column,Data_type,No_miss_Qty,%Missing,Missing_Qty
0,name,[<class 'str'>],277783,0.00,0
1,address,"[<class 'str'>, <class 'NoneType'>]",275798,0.71,1985
2,gmap_id,[<class 'str'>],277783,0.00,0
3,description,"[<class 'NoneType'>, <class 'str'>]",80137,71.15,197646
4,latitude,[<class 'float'>],277783,0.00,0
5,longitude,[<class 'float'>],277783,0.00,0
6,category,[<class 'numpy.ndarray'>],277783,0.00,0
7,avg_rating,[<class 'float'>],277783,0.00,0
8,num_of_reviews,[<class 'int'>],277783,0.00,0
9,price,"[<class 'NoneType'>, <class 'str'>]",101239,63.55,176544
10,hours,"[<class 'numpy.ndarray'>, <class 'NoneType'>]",222694,19.83,55089
11,MISC,"[<class 'dict'>, <class 'NoneType'>]",255936,7.86,21847
12,state,"[<class 'str'>, <class 'NoneType'>]",225054,18.98,52729
13,relative_results,"[<class 'numpy.ndarray'>, <class 'NoneType'>]",229507,17.38,48276
14,url,[<class 'str'>],277783,0.00,0

In [9]:
    # Lista de columnas a eliminar
drop_col = ['price', 'url', 'hours', 'description', 'state', 'MISC', 'relative_results']
    
    # Eliminar columnas
sites_df.drop(columns=drop_col, inplace=True)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 11, Finished, Available)

In [10]:
gh_df = pd.merge(sites_df, gm_df, on = 'gmap_id', how = 'inner')

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 12, Finished, Available)

In [11]:
## Dataframe info
ut.data_summ(gh_df)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 13, Finished, Available)

        Column                           Data_type  No_miss_Qty  %Missing  Missing_Qty
        name_x                     [<class 'str'>]      4332565      0.00            0
       address [<class 'str'>, <class 'NoneType'>]      4330741      0.04         1824
       gmap_id                     [<class 'str'>]      4332565      0.00            0
      latitude                   [<class 'float'>]      4332565      0.00            0
     longitude                   [<class 'float'>]      4332565      0.00            0
      category           [<class 'numpy.ndarray'>]      4332565      0.00            0
    avg_rating                   [<class 'float'>]      4332565      0.00            0
num_of_reviews                     [<class 'int'>]      4332565      0.00            0
       user_id                   [<class 'float'>]      4332565      0.00            0
        name_y                     [<class 'str'>]      4332565      0.00            0
        rating                     [<class 'int'>]      4332565      0.00            0
          text [<class 'str'>, <class 'NoneType'>]      2444926     43.57      1887639
          date                     [<class 'str'>]      4332565      0.00            0
         state                     [<class 'str'>]      4332565      0.00            0
=====================================

,Column,Data_type,No_miss_Qty,%Missing,Missing_Qty
0,name_x,[<class 'str'>],4332565,0.00,0
1,address,"[<class 'str'>, <class 'NoneType'>]",4330741,0.04,1824
2,gmap_id,[<class 'str'>],4332565,0.00,0
3,latitude,[<class 'float'>],4332565,0.00,0
4,longitude,[<class 'float'>],4332565,0.00,0
5,category,[<class 'numpy.ndarray'>],4332565,0.00,0
6,avg_rating,[<class 'float'>],4332565,0.00,0
7,num_of_reviews,[<class 'int'>],4332565,0.00,0
8,user_id,[<class 'float'>],4332565,0.00,0
9,name_y,[<class 'str'>],4332565,0.00,0
10,rating,[<class 'int'>],4332565,0.00,0
11,text,"[<class 'str'>, <class 'NoneType'>]",2444926,43.57,1887639
12,date,[<class 'str'>],4332565,0.00,0
13,state,[<class 'str'>],4332565,0.00,0

In [12]:
##Desanidado de datos que contiene la columna "category"
dataframe = gh_df
column = 'category'
cat = ut.explode_column(dataframe, column)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 14, Finished, Available)

In [13]:
##Reemplazar valores nulos
cat = ut.replace_all_nulls(cat)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 15, Finished, Available)

In [14]:
#Visualizar todas las categorias desanidadas
unique_categories = cat['category'].unique()
for category in unique_categories:
    print(category)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 16, Finished, Available)

Korean restaurant
Restaurant
Mailing service
Courier service
Fax service
Lamination service
Mailbox rental service
Notary public
Packaging supply store
Post office
Shipping service
Seafood restaurant
Mexican restaurant
RV park
Campground
Coffee shop
Bagel shop
Bakery
Breakfast restaurant
Donut shop
Fast food restaurant
Takeout Restaurant
Modern French restaurant
Pizza restaurant
Italian restaurant
Delivery Restaurant
Public parking space
Ecological park
Skateboard park
Hamburger restaurant
American restaurant
Barbecue restaurant
Sandwich shop
Shopping mall
Art gallery
Indian restaurant
Cafeteria
Vegan restaurant
Bistro
Kosher restaurant
Vegetarian restaurant
Cafe
Lunch restaurant
Shipping and mailing service
Business center
Freight forwarding service
Office supply store
Print shop
Shredding service
Gas station
ATM
Convenience store
Chinese restaurant
Asian fusion restaurant
Chinese noodle restaurant
Dumpling restaurant
Soup restaurant
Juice shop
Health food restaurant
Health food store
Organic food store
Sunglasses store
Fashion accessories store
Gift shop
Vietnamese restaurant
Asian restaurant
Rice restaurant
Bar
Caterer
Sushi restaurant
Ramen restaurant
Motel
Japanese restaurant
Southeast Asian restaurant
Mobile home park
Mobile home dealer
Mobile home rental agency
Alternative fuel station
Ice cream shop
City park
Delivery service
Organic shop
Cake shop
Cupcake shop
Kosher grocery store
Pastry shop
Wedding bakery
Cajun restaurant
Chicken wings restaurant
French restaurant
Crêperie
Tea house
Museum
History museum
Tourist attraction
Steak house
General store
Grocery store
Lottery retailer
Propane supplier
Salad shop
Art supply store
Craft store
Furniture store
Lighting store
Picture frame shop
Stationery store
Pho restaurant
Pub
Catering food and drink supplier
Cheese shop
Market
Brunch restaurant
Filipino restaurant
Bubble tea store
Deli
Educational institution
Pottery store
Latin American restaurant
Guatemalan restaurant
Sports bar
Hunan restaurant
Coffee roasters
Wholesaler
Art museum
Thai restaurant
Puerto Rican restaurant
Diner
Oyster bar restaurant
Californian restaurant
Distillery
Seafood market
Produce market
Restaurant supply store
Cocktail bar
Wine bar
Cuban restaurant
Colombian restaurant
Tea store
Dessert shop
Theater company
Arts organization
Performing arts theater
Theater production
Check cashing service
South Asian restaurant
Tax preparation service
Bookkeeping service
Payroll service
Resort hotel
Hotel
Indoor lodging
Inn
Lodge
Mountain cabin
Rafting
Villa
Entertainment and recreation
Taco restaurant
Park
West African restaurant
African restaurant
Newspaper publisher
Office space rental agency
Business park
Call center
Conference center
Coworking space
Executive suite rental agency
Telephone answering service
Virtual office rental
Real estate
Mediterranean restaurant
Pizza delivery
Pizza Takeout
Central American restaurant
Ecuadorian restaurant
Water park
Creole restaurant
Mobile caterer
Bar & grill
Auto repair shop
Auto machine shop
Boat repair shop
Diesel engine repair service
Small engine repair service
Dinner theater
Parking garage
Theme park
State park
Dessert restaurant
Gastropub
Event venue
Gay & lesbian organization
Holiday accommodation service
Retreat center
Spiritist center
Wedding venue
Dog park
Attorney
Condominium rental agency
Travel agency
Vacation home rental agency
Snack bar
Family restaurant
Live music venue
Caribbean restaurant
Cycling park
Neapolitan restaurant
Salvadoran restaurant
Landscaping supply store
Food and drink
Tax preparation
Accountant
Association or organization
Burrito restaurant
Tex-Mex restaurant
Tattoo shop
Novelty store
Psychic
Frozen dessert supplier
Frozen yogurt shop
Convenience stores organization
Greek restaurant
Food court
Loan agency
Money order service
Money transfer service
Club
Soul food restaurant
Department of motor vehicles
Auto tag agency
Driver and vehicle licensing agency
Driver's license office
Tag agency
Title company
Fish & chips restaurant
Mexican grocery store
Lounge
Wildlife park
Pasta shop
Beauty salon
Mailbox supplier
Moving supply store
Southern restaurant (US)
Chicken restaurant
Car battery store
Car repair and maintenance
Engine rebuilding service
Mechanic
Oil change service
Transmission shop
Wheel alignment service
Cheesesteak restaurant
Tanning salon
Beer garden
Brewery
Live music bar
Buffet restaurant
Beer store
Pool hall
Wine store
Hot pot restaurant
Taiwanese restaurant
Mandarin restaurant
Fine dining restaurant
Halal restaurant
Brake shop
Japanese steakhouse
Store
Certified public accountant
Camping store
Cottage
Cabaret club
Circus
Night club
Spanish restaurant
Newspaper advertising department
European restaurant
New American restaurant
Valet parking service
Tamale shop
Pan-Asian restaurant
Tobacco shop
Glass blower
Modern Indian restaurant
Indian takeaway
Piano bar
Amusement park ride
Car wash
Hawaiian restaurant
Small appliance repair service
Digital printing service
Passport photo processor
Eclectic restaurant
Lawn mower repair service
Service establishment
Roller coaster
Copy shop
HVAC contractor
Air conditioning contractor
Air conditioning repair service
Commercial refrigeration
Commercial refrigerator supplier
Contractor
Furnace repair service
Heating contractor
Kitchen supply store
Hot dog restaurant
Book publisher
Book store
Publisher
Beer hall
Amusement park
Banquet hall
Event planner
Gluten-free restaurant
Free parking lot
Candy store
Brazilian restaurant
Karaoke
Tattoo and piercing shop
Body piercing shop
Small plates restaurant
Soup shop
Art cafe
Liquor store
Fairground
Haitian restaurant
Shabu-shabu restaurant
Blues club
Pretzel store
Wholesale bakery
Chophouse restaurant
Chinese takeaway
Delivery Chinese restaurant
Chicken shop
Retirement community
Legal aid office
Civil law attorney
Divorce lawyer
Elder law attorney
Family law attorney
Social security attorney
Athletic park
Jamaican restaurant
Italian grocery store
Self-catering accommodation
Conveyor belt sushi restaurant
Auto body shop
Auto bodywork mechanic
Auto electrical service
Auto radiator repair service
Auto tune up service
Chauffeur service
BMX park
Home goods store
Insurance agency
Auto insurance agency
Dental insurance agency
Health insurance agency
Life insurance agency
Bowling alley
Mexican torta restaurant
Memorial park
Historical place
Commercial agent
Home insurance agency
Insurance broker
Motorcycle insurance agency
Property investment
Auto air conditioning service
Car detailing service
Espresso bar
Fresh food market
Noodle shop
Traditional American restaurant
Gourmet grocery store
Manufacturer
Pie shop
Bookbinder
Bookmaker
Leather repair service
Repair service
Gyro restaurant
ATV repair shop
Box lunch supplier
Pet boarding service
Photographer
Sundae restaurant
Cider bar
Comedy club
Dart bar
Karaoke bar
Appliance store
Appliance parts supplier
Appliance repair service
Microwave oven repair service
Used appliance store
Washer & dryer repair service
Grill
Southwestern restaurant (US)
Refrigerator repair service
Artist
Painter
Painting
Middle Eastern restaurant
Nail salon
Waxing hair removal service
Falafel restaurant
Public golf course
Golf driving range
Honduran restaurant
Custom home builder
Auto dent removal service
Auto glass shop
Dairy
Marina
Coffee store
Internet cafe
Art restoration service
Exhibit
Interior designer
Mirror shop
Photo restoration service
Wood frame supplier
Indian grocery store
Science museum
Archaeological museum
Natural history museum
Fusion restaurant
Salsa bar
Dim sum restaurant
Hot dog stand
Social services organization
Bangladeshi restaurant
Sichuan restaurant
Government office
City Hall
Mongolian barbecue restaurant
Authentic Japanese restaurant
Diesel fuel supplier
Sushi takeaway
Legal services
Bankruptcy service
Divorce service
Meat products
Zoo
Party planner
Butcher shop
Department store
Bar restaurant furniture store
Vegetarian cafe and deli
Dairy store
Media company
Film production company
Gambling house
Brewpub
Boutique
Jewelry store
Tapas restaurant
Soft drinks shop
Water cooler supplier
Pancake restaurant
Korean barbecue restaurant
Ethiopian restaurant
Electric vehicle charging station
Fraternal organization
Organic restaurant
Record store
Comic book store
Used CD store
Video game store
British restaurant
Photo lab
Dollar store
Discount store
Party store
School supply store
Variety store
Armenian restaurant
Kebab shop
Russian restaurant
Dominican restaurant
Insurance company
Education center
Historical landmark
Historical society
Local history museum
Fried chicken takeaway
Uzbeki restaurant
Crab house
Georgian restaurant
Auto parts store
Fingerprinting service
Photography service
French steakhouse restaurant
Haute French restaurant
Tire shop
Wheel store
Gun shop
Hunting store
Sporting goods store
Antique furniture store
Antique store
Northern Italian restaurant
Southern Italian restaurant
Grill store
Modern European restaurant
Tapas bar
RV supply store
RV dealer
Real estate rental agency
Video arcade
Irish pub
Irish restaurant
Generator shop
Lawn mower store
Sharpening service
Hair salon
Cookie shop
Barber shop
Party equipment rental service
Bouncy castle hire
Children's party service
Event management company
Pakistani restaurant
Truck repair shop
BMW dealer
Chevrolet dealer
Ford dealer
Honda dealer
Toyota dealer
Grocery delivery service
Hostel
Turkish restaurant
Property management company
Cutlery store
Vitamin & supplements store
Car inspection station
Motorcycle repair shop
Mexican goods store
Afghani restaurant
Passport agent
Homeowners' association
Udon noodle restaurant
Scandinavian restaurant
Art dealer
Pet friendly accommodation
Beer distributor
Permanent make-up clinic
Tattoo removal service
Eastern European restaurant
Ukrainian restaurant
Hoagie restaurant
Winery
Newspaper distribution
Polish restaurant
Raw food restaurant
Pan-Latin restaurant
South American restaurant
Bowling supply shop
Recreation center
Catering
Lawn equipment rental service
Equipment rental agency
Hardware store
Electrical supply store
Garden center
Paint store
Plumbing supply store
Tool rental service
Tool repair shop
Non-profit organization
Historical place museum
Ham shop
Israeli restaurant
Tractor dealer
Tractor repair shop
Country club
Candle store
Golf instructor
Sports complex
Volleyball court
Cantonese restaurant
Children's museum
Social club
Miniature golf course
Art handcraft
Greeting card shop
Handicraft
Souvenir store
Dog day care center
Pet groomer
Restaurant or cafe
Food
Auto restoration service
Car stereo store
Used car dealer
Muffler shop
Used tire shop
Children's amusement center
Cell phone store
Computer repair service
Electronics repair shop
Screen repair service
Dance school
Childrens club
Cultural center
Dance company
Ethnic restaurant
Porridge restaurant
Beauty supply store
Cosmetics store
Hair extensions supplier
Health and beauty shop
Wig shop
Peruvian restaurant
Produce wholesaler
Water sports equipment rental service
Wi-Fi spot
Food products supplier
Casino
Bed & breakfast
Fitness center
Golf course
Indoor swimming pool
Tennis club
Construction equipment supplier
Farm equipment repair service
Men's clothing store
Clothing store
Down home cooking restaurant
Ear piercing service
Movie theater
Meat processor
Pool billard club
Advertising agency
Internet service provider
Marketing agency
Modern art museum
Function room facility
Supermarket
Airport parking lot
Popcorn store
Croatian restaurant
Accounting firm
Income tax help association
Tax attorney
Tax consultant
Tax department
Australian restaurant
National forest
Japanese curry restaurant
Vintage clothing store
Women's clothing store
Indonesian restaurant
Malaysian restaurant
Translator
Paraguayan restaurant
Lithuanian restaurant
Serviced accommodation
College
Public university
Holiday park
Garden machinery supplier
Weight loss service
Disposable tableware supplier
Paper bag supplier
Professional services
Concert hall
Traditional restaurant
Art center
Community center
Real estate agents
Continental restaurant
Charcuterie
Lebanese restaurant
Coin dealer
Collectibles store
Thrift store
Boat rental service
Boat tour agency
Canoe & kayak rental service
Tour agency
Towing service
Auto wrecker
Hydraulic repair service
Transportation service
Cigar shop
Chocolate shop
Chocolate artisan
Japanese sweets restaurant
Playground
Kyoto style Japanese restaurant
Teppanyaki restaurant
Country food restaurant
Amusement center
Corporate entertainment service
Fuel supplier
Nuevo Latino restaurant
Wedding service
Portuguese restaurant
Map store
Wedding planner
Aquatic centre
Natural goods store
Equipment supplier
Farmers' market
Animals
Farm
Haunted house
Honey farm
Pumpkin patch
Apartment complex
Apartment building
Extended stay hotel
Furnished apartment building
Parking lot
Persian restaurant
South African restaurant
Fish and chips takeaway
Battery store
Public bathroom
Vaporizer store
Batting cage center
Moroccan restaurant
Izakaya restaurant
Yakitori restaurant
Hookah bar
Food store
Yemenite restaurant
Desktop publishing service
Telecommunications service provider
Farm equipment supplier
Firewood supplier
Lawn care service
Art school
African goods store
Beverage distributor
Fishing pier
Hiking area
Hunting area
Swimming lake
Place of worship
Comic cafe
Game store
Golf club
Japanese regional restaurant
Rail museum
Billiards supply store
Farm shop
Picnic ground
Laundry
Shanghainese restaurant
Air compressor repair service
Cabin rental agency
Flea market
Bait shop
Soup kitchen
Off roading area
Seafood
Seafood wholesaler
Bocce ball court
Fruit and vegetable store
Fruits wholesaler
Footwear wholesaler
New England restaurant
Vineyard
Poster store
Camp
German restaurant
Car dealer
Vehicle inspection
Jewish restaurant
Blacksmith
Class
Coppersmith
Training centre
Training school
Welding supply store
Housing development
Manufactured home transporter
Real estate agency
Trailer rental service
Nature preserve
Indoor golf course
Hong Kong style fast food restaurant
Importer
Computer service
Copying supply store
Key duplication service
Shipping company
Jazz club
Hakka restaurant
Metaphysical supply store
Rock shop
Brasserie
Escape room center
Cider mill
Po’ boys restaurant
Plant nursery
National park
Indoor playground
Food service
Bulgarian restaurant
Serbian restaurant
Store equipment supplier
Church
Lutheran church
Log cabins
Coffee stand
Obanzai restaurant
East African restaurant
Law school
North African restaurant
Dance club
Learning center
Toy store
Hookah store
Soccer field
Softball field
Wildlife refuge
Childrens store
T-shirt store
Disc golf course
Gas shop
Argentinian restaurant
Laser tag center
Dentist
Alternative medicine practitioner
Dental clinic
Dental implants periodontist
Doctor
Medical Center
Medical spa
Naturopathic practitioner
Orthodontist
Nudist park
Wholesale grocer
Singaporean restaurant
Swedish restaurant
Nepalese restaurant
Lodging
Tool store
Venezuelan restaurant
Adventure sports center
Off track betting shop
Home improvement store
Art studio
Immigration & naturalization service
Boat ramp
Fishing store
Marine supply store
Weigh station
Library
News service
Rest stop
Painting studio
Indian Muslim restaurant
Ice skating rink
Veterinarian
Charity
Hockey club
Christmas store
Handbags shop
Interior Decorator
Swimming pool
Meeting planning service
Laotian restaurant
Nicaraguan restaurant
Research institute
Belgian restaurant
Japanese confectionery shop
Musician
Ballet school
BBQ area
Açaí shop
Heritage museum
Camera store
Barbecue area
Meat dish restaurant
Public library
Genealogist
Business management consultant
Estate planning attorney
Paralegal services provider
Passport office
Herb shop
Holistic medicine practitioner
Massage therapist
Nutritionist
Used book store
Roller skating rink
Skate shop
Skateboard shop
Corporate office
Food producer
Airport shuttle service
Wok restaurant
North Eastern Indian restaurant
Adult entertainment club
Go-kart track
Contemporary Louisiana restaurant
Patisserie
Tofu restaurant
Cambodian restaurant
Gym
Agricultural service
Meeting room
Canoeing area
Christmas tree farm
Dog trainer
Dog walker
Pet sitter
Pet trainer
Country park
Building materials store
Building materials supplier
Kitchen remodeler
Lumber store
Millwork shop
Nightlife
ATV dealer
Winemaking supply store
Asian grocery store
Cape Verdean restaurant
Army museum
Sicilian restaurant
Air compressor supplier
Industrial equipment supplier
Trailer dealer
Trailer supply store
Meat wholesaler
Warehouse club
Outlet mall
Punjabi restaurant
Wine cellar
Tourist information center
Planetarium
Visitor center
Egyptian restaurant
Shoe store
Sportswear store
Car racing track
Fishing camp
Pottery classes
Summer camp
Self service restaurant
DJ service
Food bank
Czech restaurant
Helium gas supplier
Technology museum
Seafood donburi restaurant
Syokudo and Teishoku restaurant
Sports activity location
Golf shop
Music store
Truck stop
Hair extension technician
Hairdresser
Dutch restaurant
Yakiniku restaurant
Beach volleyball court
Pharmacy
Perfume store
Wellness center
Culture
Religious destination
Religious organization
Tour operator
Auto spring shop
Dog breeder
Kennel
Apartment rental agency
Couscous restaurant
Ice supplier
Beach pavillion
Graphic designer
Photo shop
Auction house
Appraiser
Estate appraiser
Toy museum
Portrait studio
Movie studio
Skating instructor
New Zealand restaurant
Spice store
English restaurant
Glass cutting service
Festival
Roman restaurant
High ropes course
Rock climbing
Tibetan restaurant
Tattoo artist
Student dormitory
Syrian restaurant
Art
Recreation
Korean beef restaurant
Korean rib restaurant
Paintball center
Butcher shop deli
Austrian restaurant
Landmark
Stage
Gift basket store
Gift wrap store
Animal feed store
Diagnostic center
Excavating contractor
Window tinting service
Costume store
After school program
Personal trainer
Preschool
Wellness program
Asturian restaurant
Boat dealer
BMX track
National museum
War museum
Private golf course
Kazakhstani restaurant
Body arts
Sports nutrition store
Tent rental service
Romanian restaurant
Fishing pond
RV repair shop
Truck rental agency
Recording studio
Sweets and dessert buffet
Japanized western restaurant
Vacuum cleaner store
Cell phone accessory store
Mobile phone repair shop
Vacuum cleaner repair shop
Parking lot for motorcycles
Salvage yard
Boat storage facility
Beauty product supplier
Condiments supplier
Tea market place
Sri Lankan restaurant
Frozen food store
Hawaiian goods store
Glass repair service
Food manufacturer
Janitorial equipment supplier
Cemetery
Wedding buffet
Ski resort
Horseback riding service
Bedroom furniture store
Used furniture store
Maritime museum
Boat club
Commercial real estate agency
Retail space rental agency
Storage facility
Trucking company
Modular home dealer
Coffee wholesaler
Cannabis store
Self-storage facility
Dance restaurant
Pawn shop
Business development service
Childrens cafe
Paper distributor
Musical club
Immigration attorney
Clothes market
Roller skating club
Japanese grocery store
Household goods wholesaler
Renter's insurance agency
Fastener supplier
Safety equipment supplier
Pozole restaurant
Drug testing service
Funeral home
Cremation service
Funeral director
Mortuary
Archive
Biryani restaurant
Typing service
Sukiyaki and Shabu Shabu restaurant
Smog inspection station
Ethnographic museum
Shawarma restaurant
Wedding chapel
Auto sunroof shop
Yoga studio
Technology park
Chapel
Cottage rental
Loss adjuster
Small claims assistance service
Digital printer
Animal hospital
Refrigerator store
Baseball
Outdoor swimming pool
Fishing area
Cleaning products supplier
Boat accessories supplier
Outboard motor store
Yacht broker
Flag store
Financial consultant
Financial planner
Investment service
Mercedes-Benz dealer
Porsche dealer
Beverages
Welder
Construction
Federal government office
Forestry service
Archery range
Shooting range
SCUBA instructor
Dive shop
Upholstery shop
Danish restaurant
Amusement machine supplier
Dart supply store
Baby store
Hair removal service
Senior citizen center

In [15]:
#Eliminar datos correspondientes a negocios que no son de nuestro interes a procesar

keywords = ['museum', 'park', 'Hotel', 'Motel', 'Hostel', 'restaurant', 'Restaurant', 'forest', 'gallery', 'mall', 'pub', 'Zoo', 'roller coaster']

# Convertir las palabras clave a minúsculas para que la búsqueda sea insensible a mayúsculas
keywords_lower = [keyword.lower() for keyword in keywords]

# Crear una máscara booleana para filtrar las filas
mask = cat['category'].str.lower().str.contains('|'.join(keywords_lower))

# Aplicar la máscara para conservar solo las filas que contienen las palabras clave
gh_df = cat[mask]

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 17, Finished, Available)

In [16]:
##Aplicar filtro
gh_df = gh_df.reset_index(drop=True)
gh_df

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 18, Finished, Available)

,name_x,address,gmap_id,latitude,longitude,category,avg_rating,num_of_reviews,user_id,name_y,rating,text,date,state
0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.292130,Korean restaurant,4.4,18,1.089912e+20,Song Ro,5,Love there korean rice cake.,2021-01-06 05:12:07,California
1,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.292130,Korean restaurant,4.4,18,1.112903e+20,Rafa Robles,5,Good very good,2021-02-09 05:47:28,California
2,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.292130,Korean restaurant,4.4,18,1.126404e+20,David Han,4,They make Korean traditional food very properly.,2020-03-08 05:04:42,California
3,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.292130,Korean restaurant,4.4,18,1.174403e+20,Anthony Kim,5,Short ribs are very delicious.,2019-03-07 05:56:56,California
4,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.292130,Korean restaurant,4.4,18,1.005808e+20,Mario Marzouk,5,Great food and prices the portions are large,2017-05-16 05:01:41,California
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10298003,The Green Room Of Libertyville,"The Green Room Of Libertyville, 624 Milwaukee ...",0x880f96c84b0ef57b:0xe75b67b15a2cfdad,42.289450,-87.954386,Restaurant,4.6,228,1.174275e+20,Max Eggers,3,ND,2019-01-13 04:40:40,Illinois
10298004,The Green Room Of Libertyville,"The Green Room Of Libertyville, 624 Milwaukee ...",0x880f96c84b0ef57b:0xe75b67b15a2cfdad,42.289450,-87.954386,Restaurant,4.6,228,1.077471e+20,Brian Lawton,5,ND,2019-10-20 04:31:09,Illinois
10298005,The Green Room Of Libertyville,"The Green Room Of Libertyville, 624 Milwaukee ...",0x880f96c84b0ef57b:0xe75b67b15a2cfdad,42.289450,-87.954386,Restaurant,4.6,228,1.114333e+20,Christopher Cantagallo,4,ND,2017-10-18 13:47:06,Illinois
10298006,The Green Room Of Libertyville,"The Green Room Of Libertyville, 624 Milwaukee ...",0x880f96c84b0ef57b:0xe75b67b15a2cfdad,42.289450,-87.954386,Restaurant,4.6,228,1.103616e+20,Saira S,5,ND,2019-01-09 11:38:23,Illinois
10298007,The Green Room Of Libertyville,"The Green Room Of Libertyville, 624 Milwaukee ...",0x880f96c84b0ef57b:0xe75b67b15a2cfdad,42.289450,-87.954386,Restaurant,4.6,228,1.004569e+20,Cicero Holmes,4,ND,2018-10-27 14:32:01,Illinois

In [17]:
##agrupar nuevamente las categorias y el resto de la información
gmap = ut.group_column(gh_df, 'category')
gmap.head(2)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 19, Finished, Available)

,name_x,address,gmap_id,latitude,longitude,avg_rating,num_of_reviews,user_id,name_y,rating,text,date,state,category
0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.29213,4.4,18,1.089912e+20,Song Ro,5,Love there korean rice cake.,2021-01-06 05:12:07,California,[Korean restaurant]
1,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.29213,4.4,18,1.112903e+20,Rafa Robles,5,Good very good,2021-02-09 05:47:28,California,[Korean restaurant]

In [18]:
df1 = gmap[['name_x', 'longitude', 'latitude']]
df1

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 20, Finished, Available)

                                  name_x   longitude   latitude
0                           San Soo Dang -118.292130  34.058092
1                           San Soo Dang -118.292130  34.058092
2                           San Soo Dang -118.292130  34.058092
3                           San Soo Dang -118.292130  34.058092
4                           San Soo Dang -118.292130  34.058092
...                                  ...         ...        ...
10298003  The Green Room Of Libertyville  -87.954386  42.289450
10298004  The Green Room Of Libertyville  -87.954386  42.289450
10298005  The Green Room Of Libertyville  -87.954386  42.289450
10298006  The Green Room Of Libertyville  -87.954386  42.289450
10298007  The Green Room Of Libertyville  -87.954386  42.289450

[4328762 rows x 3 columns]

In [19]:
df1 = df1.drop_duplicates().reset_index(drop=True)
df1

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 21, Finished, Available)

                               name_x   longitude   latitude
0                        San Soo Dang -118.292130  34.058092
1                        Vons Chicken -118.010855  33.916402
2                        Mail Station  -82.508387  27.389683
3                  Long John Silver's  -87.296512  41.472375
4                  Taqueria El Patron  -92.040551  30.260098
...                               ...         ...        ...
49932              Farmer Meat Market  -91.169125  30.493538
49933              China King Express  -78.988253  42.698185
49934                       D Cuisine  -87.644375  41.932084
49935        House of Gourmet -- 食全食美  -78.827337  42.980251
49936  The Green Room Of Libertyville  -87.954386  42.289450

[49937 rows x 3 columns]

In [20]:
#Agarra las cordenadas y a partir de la API se le asigna la ciudad donde está localizada

file_location = '/lakehouse/default/Files/df_database/city.parquet'
api_key = 'AkAEqJCFD-79UwAbaZa2rFXHVTUb1GEJb-3u5DkEIYV7c-uHbl50Ij7frtZdO3Y5'
df_city = ut.city_dataframe(df1, file_location, api_key)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 22, Finished, Available)

In [21]:
df_city.head(2)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 23, Finished, Available)

         name_x   longitude   latitude         City
0  San Soo Dang -118.292130  34.058092  Los Angeles
1  Vons Chicken -118.010855  33.916402    La Mirada

In [22]:
ut.data_summ(df_city)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 24, Finished, Available)

   Column                           Data_type  No_miss_Qty  %Missing  Missing_Qty
   name_x                     [<class 'str'>]        49937      0.00            0
longitude                   [<class 'float'>]        49937      0.00            0
 latitude                   [<class 'float'>]        49937      0.00            0
     City [<class 'str'>, <class 'NoneType'>]        45397      9.09         4540
=====================================

,Column,Data_type,No_miss_Qty,%Missing,Missing_Qty
0,name_x,[<class 'str'>],49937,0.00,0
1,longitude,[<class 'float'>],49937,0.00,0
2,latitude,[<class 'float'>],49937,0.00,0
3,City,"[<class 'str'>, <class 'NoneType'>]",45397,9.09,4540

In [23]:
df_city = df_city.dropna(subset=['City'])

# Restablecer los índices después de eliminar filas
df_city = df_city.reset_index(drop=True)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 25, Finished, Available)

In [24]:
df_maps = pd.merge(gmap, df_city, on=["name_x", "longitude", "latitude"], how = "inner")

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 26, Finished, Available)

In [25]:
df_maps["count_checkin"] = 1

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 27, Finished, Available)

In [26]:
df_maps.head(2)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 28, Finished, Available)

,name_x,address,gmap_id,latitude,longitude,avg_rating,num_of_reviews,user_id,name_y,rating,text,date,state,category,City,count_checkin
0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.29213,4.4,18,1.089912e+20,Song Ro,5,Love there korean rice cake.,2021-01-06 05:12:07,California,[Korean restaurant],Los Angeles,1
1,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,34.058092,-118.29213,4.4,18,1.112903e+20,Rafa Robles,5,Good very good,2021-02-09 05:47:28,California,[Korean restaurant],Los Angeles,1

In [27]:
df_maps = df_maps[["name_x", "address", "City", "state", "latitude", "longitude", "avg_rating", "num_of_reviews", "date", "count_checkin", "user_id", "rating", "text", "name_y", "category"]]

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 29, Finished, Available)

In [28]:
df_maps = df_maps.rename(columns={
    "name_x": 'Business_Name',
    "address": 'Address',
    "City": 'City',
    "state": 'State',
    "latitude": 'Latitude',
    "longitude": 'Longitude',
    "avg_rating": 'Ranking',
    "num_of_reviews": 'Review_Count',
    "date" : "Date",
    "count_checkin": 'Checkin_Count',
    "user_id": 'User_Id',
    "rating": 'Stars',
    "text": 'Text',
    "name_y": 'User_Name',
    "category": 'Category'
})

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 30, Finished, Available)

In [29]:
df_maps.head(2)

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 31, Finished, Available)

,Business_Name,Address,City,State,Latitude,Longitude,Ranking,Review_Count,Date,Checkin_Count,User_Id,Stars,Text,User_Name,Category
0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",Los Angeles,California,34.058092,-118.29213,4.4,18,2021-01-06 05:12:07,1,1.089912e+20,5,Love there korean rice cake.,Song Ro,[Korean restaurant]
1,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",Los Angeles,California,34.058092,-118.29213,4.4,18,2021-02-09 05:47:28,1,1.112903e+20,5,Good very good,Rafa Robles,[Korean restaurant]

In [30]:
df_maps.to_parquet('/lakehouse/default/Files/df_database/files_to_EDA/Maps_to_EDA.parquet')

StatementMeta(, 905966e0-c7c4-4400-aa7f-c5319188fea7, 32, Finished, Available)