# ETL for Yelp data Files 

We will perform the extraction, transformation and data loading of the data included in the files provided in the Yelp folder

### 1- IMPORT LIBRARIES

In [1]:
import builtin.utils as ut
import pandas as pd
from ast import literal_eval
import ast

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 3, Finished, Available)

___
### 2- LOAD CLEAN DATA

First we are going to extract all the information from the data lake by using the Pandas library, and proceed to analyze the dataframes one by one

In [2]:
yelp_bus = '/lakehouse/default/Files/df_database/Yelp_parquet/business.pkl.parquet'
yelp_check = '/lakehouse/default/Files/df_database/Yelp_parquet/checkin.json.parquet'
yelp_review = '/lakehouse/default/Files/df_database/Yelp_parquet/review.json.parquet'
yelp_tip = '/lakehouse/default/Files/df_database/Yelp_parquet/tip.json.parquet'
yelp_user = '/lakehouse/default/Files/df_database/Yelp_parquet/user.parquet'

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 4, Finished, Available)

In [3]:
business = pd.read_parquet(yelp_bus)
checkin = pd.read_parquet(yelp_check)
review = pd.read_parquet(yelp_review)
tip = pd.read_parquet(yelp_tip)
user = pd.read_parquet(yelp_user)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 5, Finished, Available)

Now we have the following dataframes:

- Business
- Checkin
- Review
- Tip
- User

___
### 3 - TRANSFORM

#### 3.1 Business Dataframe

In [4]:
business.head()

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 6, Finished, Available)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,None,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,None,63123,38.551126,-90.335695,3.0,15,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Shipping Centers, Local Services, Notaries, Ma...","{'Friday': '8:0-18:30', 'Monday': '0:0-0:0', '..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,None,85711,32.223236,-110.880452,3.5,22,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Department Stores, Shopping, Fashion, Home & G...","{'Friday': '8:0-23:0', 'Monday': '8:0-22:0', '..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,19107,39.955505,-75.155564,4.0,80,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Friday': '7:0-21:0', 'Monday': '7:0-20:0', '..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,18054,40.338183,-75.471659,4.5,13,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Brewpubs, Breweries, Food","{'Friday': '12:0-22:0', 'Monday': None, 'Satur..."

In [5]:
ut.data_summ(business)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 7, Finished, Available)

      Column                            Data_type  No_miss_Qty  %Missing  Missing_Qty
 business_id                      [<class 'str'>]       150346      0.00            0
        name                      [<class 'str'>]       150346      0.00            0
     address                      [<class 'str'>]       150346      0.00            0
        city                      [<class 'str'>]       150346      0.00            0
       state  [<class 'NoneType'>, <class 'str'>]       150343      0.00            3
 postal_code                      [<class 'str'>]       150346      0.00            0
    latitude                    [<class 'float'>]       150346      0.00            0
   longitude                    [<class 'float'>]       150346      0.00            0
       stars                    [<class 'float'>]       150346      0.00            0
review_count                      [<class 'int'>]       150346      0.00            0
     is_open                      [<class 'int'>]       150346      0.00            0
  attributes [<class 'dict'>, <class 'NoneType'>]       136602      9.14        13744
  categories  [<class 'str'>, <class 'NoneType'>]       150243      0.07          103
       hours [<class 'NoneType'>, <class 'dict'>]       127123     15.45        23223
=====================================

,Column,Data_type,No_miss_Qty,%Missing,Missing_Qty
0,business_id,[<class 'str'>],150346,0.00,0
1,name,[<class 'str'>],150346,0.00,0
2,address,[<class 'str'>],150346,0.00,0
3,city,[<class 'str'>],150346,0.00,0
4,state,"[<class 'NoneType'>, <class 'str'>]",150343,0.00,3
5,postal_code,[<class 'str'>],150346,0.00,0
6,latitude,[<class 'float'>],150346,0.00,0
7,longitude,[<class 'float'>],150346,0.00,0
8,stars,[<class 'float'>],150346,0.00,0
9,review_count,[<class 'int'>],150346,0.00,0
10,is_open,[<class 'int'>],150346,0.00,0
11,attributes,"[<class 'dict'>, <class 'NoneType'>]",136602,9.14,13744
12,categories,"[<class 'str'>, <class 'NoneType'>]",150243,0.07,103
13,hours,"[<class 'NoneType'>, <class 'dict'>]",127123,15.45,23223


The content ~head~ of the dataframe is observed, it has 14 columns with the information of:

- **Businnes ID**:    STR Contains business identification 
- **Name**:    STR Contains the name of the business
- **Address**:    STR Contains the complete address of the business
- **City**:    STR Contains the city where the business is located
- **State**:    STR Contains the state where the business is located
- **Postal Code**:    STR Contains the postal code of the business location
- **Latitude**:    FLOAT Contains Latitude
- **Longitude**:    FLOAT Contains Longitude
- **Is Open**:    INT Contains 1 and 0 to indicate whether the business is open or closed respectively 
- **Stars**:    FLOAT Contains the number of stars, between 0 and 5
- **Review_count**:    INT Contains the count of reviews of the business
- **Attributes**:    STR Contains business attributes as values
- **Categories**:    STR Contains business categories
- **Hours**:    STR Contains the hours it is open

For the project proposal that we are carrying out, several of the columns are relevant and others are not.
Therefore, we proceed to eliminate those columns that are not relevant to us, among them: "Postal_code", "is_open", "attributes", "hours"

In [6]:
business = business.drop(["postal_code", "is_open", "attributes", "hours"], axis=1)
business

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 8, Finished, Available)

,business_id,name,address,city,state,latitude,longitude,stars,review_count,categories
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,None,34.426679,-119.711197,5.0,7,"Doctors, Traditional Chinese Medicine, Naturop..."
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,None,38.551126,-90.335695,3.0,15,"Shipping Centers, Local Services, Notaries, Ma..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,None,32.223236,-110.880452,3.5,22,"Department Stores, Shopping, Fashion, Home & G..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,40.338183,-75.471659,4.5,13,"Brewpubs, Breweries, Food"
...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,IN,53.468419,-113.492054,3.0,13,"Nail Salons, Beauty & Spas"
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,DE,36.115118,-86.766925,4.0,5,"Pets, Nurseries & Gardening, Pet Stores, Hobby..."
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,AB,39.908707,-86.065088,3.5,8,"Shopping, Jewelry, Piercing, Toy Stores, Beaut..."
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,AB,38.782351,-89.950558,4.0,24,"Fitness/Exercise Equipment, Eyewear & Optician..."
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,TN,27.771002,-82.394910,4.5,9,"Beauty & Spas, Permanent Makeup, Piercing, Tattoo"

In [7]:
business["categories"] = business["categories"].apply(lambda x: x.split(', ') if pd.notna(x) else [])

rt_df = ut.explode_column(business, "categories")

rt_df = ut.replace_all_nulls(rt_df)

unique_categories = rt_df['categories'].unique()
for category in unique_categories:
    print(category)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 9, Finished, Available)

Doctors
Traditional Chinese Medicine
Naturopathic/Holistic
Acupuncture
Health & Medical
Nutritionists
Shipping Centers
Local Services
Notaries
Mailbox Centers
Printing Services
Department Stores
Shopping
Fashion
Home & Garden
Electronics
Furniture Stores
Restaurants
Food
Bubble Tea
Coffee & Tea
Bakeries
Brewpubs
Breweries
Burgers
Fast Food
Sandwiches
Ice Cream & Frozen Yogurt
Sporting Goods
Shoe Stores
Sports Wear
Accessories
Synagogues
Religious Organizations
Pubs
Italian
Bars
American (Traditional)
Nightlife
Greek
Vietnamese
Food Trucks
Diners
Breakfast & Brunch
General Dentistry
Dentists
Cosmetic Dentists
Delis
Sushi Bars
Japanese
Automotive
Auto Parts & Supplies
Auto Customization
Vape Shops
Tobacco Shops
Personal Shopping
Vitamins & Supplements
Car Rental
Hotels & Travel
Truck Rental
Korean
Cafes
Wine Bars
Books
Mags
Music & Video
Bookstores
Steakhouses
Asian Fusion
Hot Dogs
Pet Services
Pet Groomers
Pets
Veterinarians
Women's Clothing
Children's Clothing
Men's Clothing
Adult
Seafood
Cocktail Bars
Pizza
Chicken Wings
Trampoline Parks
Active Life
Salad
Soup
Dance Wear
Arts & Entertainment
Social Clubs
Performing Arts
Event Planning & Services
Hotels
Eatertainment
Mobile Phones
Telecommunications
Mobile Phone Accessories
IT Services & Computer Repair
Museums
Kids Activities
Education
Playgrounds
Children's Museums
Musicians
DJs
Karaoke
Hair Salons
Hair Extensions
Beauty & Spas
Wigs
Specialty Food
Pasta Shops
DUI Law
Professional Services
Lawyers
Criminal Defense Law
Laser Hair Removal
Hair Removal
Chiropractors
Weight Loss Centers
Sports Medicine
Medical Spas
Skin Care
Candle Stores
Home Decor
Chinese
Music Venues
Internet Service Providers
Jazz & Blues
Internet Cafes
Caterers
Fitness & Instruction
Trainers
Gyms
Yoga
Real Estate Agents
Home Services
Real Estate
Health Markets
Pet Adoption
Grocery
Convenience Stores
Juice Bars & Smoothies
Ophthalmologists
Eyewear & Opticians
Optometrists
American (New)
Sports Bars
Gastropubs
Beer Bar
Uniforms
Tours
Local Flavor
Appliances & Repair
Towing
Motorcycle Rental
Motorcycle Gear
Chocolatiers & Shops
Candy Stores
Baby Gear & Furniture
Banks & Credit Unions
Financial Services
Personal Care Services
Massage
Nail Salons
Tabletop Games
Lounges
Wraps
Festivals
Beer
Wine & Spirits
Gas Stations
Keys & Locksmiths
Pet Sitting
Venues & Event Spaces
Fruits & Veggies
Antiques
Body Shops
Masonry/Concrete
Gardeners
Lawn Services
Tree Services
Landscape Architects
Contractors
Landscaping
Party & Event Planning
Mortgage Brokers
Mortgage Lenders
Physical Therapy
Jewelry
Cajun/Creole
Mexican
Couriers & Delivery Services
French
Moroccan
Mediterranean
Flooring
Handyman
Pest Control
Auction Houses
Beer Gardens
Wine Tours
Beer Tours
Drugstores
Discount Store
Public Services & Government
Libraries
Flowers & Gifts
Embroidery & Crochet
Arts & Crafts
Gift Shops
Food Delivery Services
Parenting Classes
Maternity Wear
Specialty Schools
Laundry Services
Child Care & Day Care
Barbers
Glass & Mirrors
Door Sales/Installation
Hardware Stores
Hot Tub & Pool
Pool & Hot Tub Service
Tires
Auto Repair
Oil Change Stations
Medical Centers
Diagnostic Services
Orthopedists
Spine Surgeons
Diagnostic Imaging
Custom Cakes
Desserts
Cupcakes
Car Wash
Auto Detailing
Pain Management
Osteopathic Physicians
Title Loans
Installment Loans
Check Cashing/Pay-day Loans
Organic Stores
Do-It-Yourself Food
Patisserie/Cake Shop
Live/Raw Food
Buses
Transportation
Bus Tours
Travel Agents
Travel Services
Airport Shuttles
Public Transportation
Filipino
Internal Medicine
Toy Stores
Hobby Shops
Comic Books
Painters
Decks & Railing
Pressure Washers
Bed & Breakfast
Art Classes
Knitting Supplies
Art Supplies
Barbeque
Urgent Care
Basketball Courts
Stadiums & Arenas
Professional Sports Teams
Pharmacy
Tattoo
Music & DVDs
Video Game Stores
Waxing
Eyelash Service
Life Coach
Meditation Centers
Home Cleaning
Office Cleaning
Window Washing
Parks
Swimming Pools
Hair Stylists
Dog Parks
Cinema
Resorts
Day Spas
Shaved Ice
Appliances
Chicken Shop
Wildlife Control
Apartments
Roofing
Vacation Rentals
Condominiums
Thai
Auto Glass Services
Windshield Installation & Repair
Bagels
Endodontists
Plumbing
Carpeting
Rugs
Southern
Makeup Artists
Obstetricians & Gynecologists
Carpet Cleaning
Donuts
Hiking
Mountain Biking
ATV Rentals/Tours
RV Rental
Hawaiian
Street Vendors
Irish
Trailer Dealers
RV Repair
Trailer Repair
RV Dealers
Propane
Outdoor Gear
Pediatricians
Officiants
Wedding Planning
Hookah Bars
Car Dealers
Used Car Dealers
Vegan
Party Supplies
Wholesalers
Soul Food
Mattresses
Tapas/Small Plates
Team Building Activities
Walking Tours
Scavenger Hunts
Machine Shops
Shanghainese
Szechuan
Irish Pub
Coffee Roasteries
Endocrinologists
Dermatologists
Golf Lessons
Golf Equipment
Golf
Fishing
Hunting & Fishing Supplies
Rest Stops
Bike Repair/Maintenance
Bikes
Caribbean
Trinidadian
Tex-Mex
Piercing
Orthodontists
Oral Surgeons
Ethnic Food
Bike Rentals
Gluten-Free
Food Tours
Photography Stores & Services
Art Galleries
Latin American
Blow Dry/Out Services
Eyebrow Services
Men's Hair Salons
Comfort Food
Windows Installation
Costumes
Refinishing Services
Shoe Repair
Sewing & Alterations
Radiologists
Tanning
Acai Bowls
Vegetarian
Pet Training
Pakistani
Indian
Halal
Food Stands
Public Art
Preschools
Elementary Schools
Dry Cleaning & Laundry
Animal Shelters
Seafood Markets
Movers
Self Storage
Insurance
Auto Insurance
Registration Services
Guest Houses
Musical Instruments & Teachers
Churches
Historical Tours
Community Service/Non-Profit
Family Practice
Counseling & Mental Health
Bowling
Countertop Installation
Cabinetry
Kitchen & Bath
Building Supplies
Interior Design
Military Surplus
Buffets
Medical Supplies
Laser Eye Surgery/Lasik
Hair Loss Centers
Walk-in Clinics
Empanadas
Nurseries & Gardening
Middle Eastern
Wholesale Stores
Brewing Supplies
Wineries
Cosmetology Schools
Tacos
Escape Games
Head Shops
Puerto Rican
Pet Stores
Cosmetics & Beauty Supply
Irrigation
Shutters
Siding
Watches
Jewelry Repair
Bridal
Parasailing
Beaches
Boating
Carpenters
Wallpapering
Shopping Centers
Heating & Air Conditioning/HVAC
Whiskey Bars
Session Photography
Photographers
Pet Photography
Real Estate Services
Real Estate Photography
Event Photography
Electronics Repair
Mobile Phone Repair
Gutter Services
Insulation Installation
Hospitals
Leather Goods
Furniture Reupholstery
Honduran
Security Systems
Security Services
Septic Services
Roadside Assistance
Junk Removal & Hauling
Ramen
Cannabis Collective
Cannabis Clinics
Cannabis Dispensaries
Home Window Tinting
Car Window Tinting
Vehicle Wraps
Transmission Repair
Sports Clubs
Arcades
Recreation Centers
Art Schools
Car Stereo Installation
Bespoke Clothing
Dry Cleaning
Permanent Makeup
Cryotherapy
Challenge Courses
Props
Noodles
Spanish
Formal Wear
Farmers Market
Pediatric Dentists
Massage Therapy
Imported Food
Cheesesteaks
Garage Door Services
Pretzels
African
Florists
University Housing
Property Management
Furniture Assembly
Pool & Billiards
Furniture Repair
Party Equipment Rentals
Virtual Reality Centers
Kebab
Turkish
Amusement Parks
Laser Tag
Race Tracks
Mini Golf
Go Karts
Community Centers
Day Camps
Summer Camps
Metal Fabricators
Awnings
Patio Coverings
Paint & Sip
Taxis
Signmaking
Guns & Ammo
Tea Rooms
Lebanese
Pilates
Barre Classes
Recycling Center
Gelato
Sugaring
Demolition Services
Carpet Installation
Tiling
Limos
Bar Crawl
Dive Bars
Haunted Houses
Fences & Gates
Home Inspectors
Skate Parks
Tubing
Ski Resorts
Creperies
Tutoring Centers
Test Preparation
Adult Education
Laundromat
Dance Studios
Party Bus Rentals
Appraisal Services
Fabric Stores
Lice Services
Dental Hygienists
Periodontists
Commercial Real Estate
Poke
Service Stations
Estheticians
Wheel & Rim Repair
Personal Injury Law
Radio Stations
Mass Media
Adult Entertainment
Lingerie
Dance Clubs
Falafel
Swimming Lessons/Schools
Jet Skis
Boat Charters
Boat Tours
Rafting/Kayaking
Shared Office Spaces
Psychics
Supernatural Readings
Psychic Mediums
Watch Repair
Fertility
Engraving
Graphic Design
Trophy Shops
Office Equipment
Motorcycle Repair
Tapas Bars
Outlet Stores
Pawn Shops
Gold Buyers
Outdoor Furniture Stores
Paint Stores
Fish & Chips
Smog Check Stations
Dog Walkers
Reiki
Teeth Whitening
Souvenir Shops
Thrift Stores
Donation Center
Used
Vintage & Consignment
Ranches
Farms
Kombucha
International Grocery
Taxidermy
Meat Shops
RV Parks
Campgrounds
Vinyl Records
Pool Halls
Skating Rinks
Rehabilitation Center
Kitchen Supplies
Hydroponics
Police Departments
Videos & Video Game Rental
Home Staging
Boot Camps
Peruvian
Herbs & Spices
Butcher
Gastroenterologist
Prosthodontists
Water Heater Installation/Repair
Swimwear
Employment Law
Workers Compensation Law
Water Delivery
Canadian (New)
Packing Supplies
Packing Services
Landmarks & Historical Buildings
Spiritual Shop
Religious Items
Lighting Stores
Ukrainian
Herbal Shops
Commercial Truck Repair
Farm Equipment Repair
Neurologist
Alternative Medicine
Medical Cannabis Referrals
Data Recovery
Home Theatre Installation
Home Automation
TV Mounting
Pet Boarding
Malaysian
Burmese
Amateur Sports Teams
Lighting Fixtures & Equipment
Electricians
Nail Technicians
Passport & Visa Services
Post Offices
Motorsport Vehicle Dealers
Motorsport Vehicle Repairs
Motorcycle Dealers
Shades & Blinds
Tanning Beds
Spray Tanning
Cuban
Educational Services
Vocational & Technical School
Wine Tasting Room
Personal Chefs
Divorce & Family Law
Legal Services
Oncologist
Surgeons
Flea Markets
Architects
Structural Engineers
Air Duct Cleaning
Martial Arts
Acne Treatment
Skate Shops
Surfing
Sicilian
Shoe Shine
Generator Installation/Repair
Floral Designers
Computers
Themed Cafes
Soccer
Water Purification Services
Water Suppliers
Utilities
Marketing
Web Design
Home Network Installation
Aestheticians
Plastic Surgeons
Damage Restoration
Advertising
Screen Printing
Excavation Services
Assisted Living Facilities
Retirement Homes
Memory Care
Cycling Classes
Aerial Fitness
Car Buyers
Cultural Center
Ear Nose & Throat
Hearing Aid Providers
Gay Bars
Driving Schools
Drywall Installation & Repair
Financial Advising
Accountants
Tax Services
Investing
Gun/Rifle Ranges
Firearm Training
Psychiatrists
Laboratory Testing
Airports
Solar Installation
Sardinian
Laotian
Teppanyaki
Urologists
Midwives
Boxing
Dominican
Plus Size Fashion
Billing Services
Cardio Classes
Flight Instruction
Aerial Tours
Framing
Badminton
Interval Training Gyms
Audiologist
Occupational Therapy
Speech Therapists
Pool Cleaners
Sunglasses
Climbing
Ethiopian
House Sitters
Pet Hospice
Pet Transportation
Recording & Rehearsal Studios
Print Media
Digitizing Services
Screen Printing/T-Shirt Printing
Roof Inspectors
Airport Lounges
Television Service Providers
Parking
Food Court
Life Insurance
Scuba Diving
Diving
Comedy Clubs
Persian/Iranian
Rheumatologists
Hong Kong Style Cafe
Taiwanese
Fireplace Services
Allergists
Cosmetic Surgeons
Reflexology
Cardiologists
Gymnastics
Archery
ND
Bookkeepers
Payroll Services
Botanical Gardens
Blood & Plasma Donation Centers
Bartenders
Podiatrists
General Litigation
Modern European
Car Auctions
Pan Asian
Casinos
New Mexican Cuisine
Wine Tasting Classes
Tasting Classes
Donairs
Oriental
Funeral Services & Cemeteries
Surf Schools
Paddleboarding
Beach Equipment Rentals
Indoor Playcentre
Private Tutors
Jails & Prisons
Bingo Halls
Mobility Equipment Sales & Services
Home & Rental Insurance
Boat Repair
Cards & Stationery
Massage Schools
Childbirth Education
Environmental Testing
Auto Loan Providers
Grilling Equipment
German
Cremation Services
Business Consulting
Water Stores
Lakes
Employment Agencies
Cheese Shops
Private Investigation
IV Hydration
Christmas Trees
Arabic
Tiki Bars
Argentine
Golf Equipment Shops
Safe Stores
Departments of Motor Vehicles
Middle Schools & High Schools
Waldorf Schools
Junkyards
Reproductive Health Services
Horse Equipment Shops
Self-defense Classes
Kickboxing
Muay Thai
Float Spa
Gunsmith
Fire Protection Services
Waterproofing
Aquarium Services
Aquariums
Ayurveda
Paint-Your-Own Pottery
Portuguese
Dim Sum
Pickleball
Hot Pot
Country Clubs
Kitchen Incubators
Motorcycle Parts & Supplies
Saunas
Emergency Pet Hospital
Dance Schools
Town Car Service
Clock Repair
Balloon Services
Outdoor Power Equipment Services
Farming Equipment
Emergency Rooms
Anesthesiologists
Orthotics
Boat Dealers
Real Estate Law
Bankruptcy Law
Kids Hair Salons
Fitness/Exercise Equipment
Livestock Feed & Supply
Machine & Tool Rental
Trailer Rental
Matchmakers
Tennis
Boudoir Photography
EV Charging Stations
Pet Breeders
Home Organization
Battery Stores
Zoos
Petting Zoos
Art Restoration
Fondue
Poutineries
Threading Services
Piano Stores
Piano Services
Musical Instrument Services
Music Production Services
Snow Removal
Karate
Kosher
Glass Blowing
Axe Throwing
Henna Artists
Customized Merchandise
Hats
Grout Services
Bike Sharing
Chimney Sweeps
Ultrasound Imaging Centers
Macarons
Fingerprinting
Sleep Specialists
Dive Shops
Home Developers
Mobile Home Repair
Cantonese
Body Contouring
Pet Cremation Services
Clothing Rental
Medical Transportation
Brazilian Jiu-jitsu
Firewood
Art Tours
Leisure Centers
Newspapers & Magazines
Observatories
Brasseries
Distilleries
Used Bookstore
Auto Upholstery
Yelp Events
Personal Assistants
Salvadoran
Bounce House Rentals
Circuit Training Gyms
Cabaret
Mongolian
Astrologers
Knife Sharpening
Lactation Services
British
Water Parks
Art Space Rentals
Airlines
Waffles
Piano Bars
Health Retreats
Hydrotherapy
Television Stations
Perfume
Airport Terminals
Speakeasies
Religious Schools
Syrian
Vacation Rental Agents
Valet Services
Colleges & Universities
Commercial Truck Dealers
Traffic Schools
Popcorn Shops
Pop-Up Restaurants
Hospice
Armenian
Hydro-jetting
Ski & Snowboard Shops
International
Cigar Bars
Well Drilling
Special Education
Wedding Chapels
Strip Clubs
Business Law
Estate Planning Law
Wills
Trusts
& Probates
Local Fish Stores
Cooking Schools
Venezuelan
Prenatal/Perinatal Care
Ethnic Grocery
Video/Film Production
Cooking Classes
Disc Golf
Mobile Dent Repair
Magicians
Halotherapy
Colombian
Brazilian
Haitian
Pet Insurance
Free Diving
Bus Rental
Public Relations
Russian
Bird Shops
Hockey Equipment
Czech
Himalayan/Nepalese
Surf Shop
Home Energy Auditors
Doulas
Placenta Encapsulations
Shredding Services
Delicatessen
Courthouses
Hostels
Homeowner Association
Bartending Schools
Home Health Care
Tui Na
Art Museums
Foundation Repair
Guitar Stores
Club Crawl
Smokehouse
High Fidelity Audio Equipment
Polish
Social Security Law
Health Insurance Offices
Colonics
Rock Climbing
Business Financing
Hainan
Dumpster Rental
Psychologists
Attraction Farms
Pick Your Own Farms
Ticket Sales
Photo Booth Rentals
Bicycle Paths
Afghan
Cafeteria
Cambodian
Cideries
Language Schools
Skilled Nursing
Career Counseling
Auto Security
Estate Liquidation
Videographers
Immigration Law
Tuscan
Restaurant Supplies
Hypnosis/Hypnotherapy
Gemstones & Minerals
Public Markets
Car Brokers
Car Share Services
Somali
Architectural Tours
Olive Oil
Tattoo Removal
Indonesian
Private Schools
Shaved Snow
Powder Coating
Train Stations
Batting Cages
Pet Waste Removal
Nanny Services
Food Banks
Champagne Bars
Environmental Abatement
Health Coach
Senegalese
Coffee & Tea Supplies
Snorkeling
Bike Repair
Bicycles
Crane Services
Holiday Decorations
Ethical Grocery
Immunodermatologists
Vehicle Shipping
Coffeeshops
Talent Agencies
Party Bike Rentals
Horseback Riding
Beverage Store
Luggage
Safety Equipment
Car Inspectors
Taekwondo
Pole Dancing Classes
Nursing Schools
Scooter Rentals
Pop-up Shops
Addiction Medicine
Photography Classes
Paintball
Drive-Thru Bars
Trains
Bike tours
Flowers
Races & Competitions
Squash
Translation Services
Sports Betting
Nephrologists
Stucco Services
Audio/Visual Equipment Rental
Nurse Practitioner
Grill Services
Emergency Medicine
Singaporean
CPR Classes
Preventive Medicine
Striptease Dancers
Qi Gong
Tai Chi
Honey
Undersea/Hyperbaric Medicine
Software Development
Fireworks
LAN Centers
Trivia Hosts
Land Surveying
Reptile Shops
Stonemasons
Vascular Medicine
Phlebologists
Bistros
Horse Boarding
Airsoft
Crisis Pregnancy Centers
Faith-based Crisis Pregnancy Centers
Traffic Ticketing Law
Meaderies
Austrian
Mobile Home Parks
Commissioned Artists
Baseball Fields
Pumpkin Patches
Marinas
Tenant and Eviction Law
Proctologists
Parent Cafes
Basque
Tableware
Mediators
Debt Relief Services
Drive-In Theater
Pulmonologist
Chinese Martial Arts
Calabrian
Editorial Services
Playsets
Country Dance Halls
Iberian
Australian
Medical Law
Gerontologists
Japanese Curry
Buddhist Temples
Private Jet Charter
Dietitians
Hot Air Balloons
Montessori Schools
South African
Prosthetics
Ski Schools
Dinner Theater
Animal Physical Therapy
Visitor Centers
Face Painting
Izakaya
Nicaraguan
Drones
Golf Cart Dealers
Bangladeshi
Carpet Dyeing
Municipality
Product Design
Holistic Animal Care
Drama Schools
Concept Shops
Scottish
Opera & Ballet
Adoption Services
Pancakes
Unofficial Yelp Events
Flyboarding
Electricity Suppliers
Indoor Landscaping
Game Truck Rental
Rolfing
Backflow Services
Portable Toilet Services
DIY Auto Shop
Belgian
CSA
General Festivals
Artificial Turf
Racing Experience
Lahmacun
Infectious Disease Specialists
Pedicabs
Egyptian
Retina Specialists
Clowns
Party Characters
Sri Lankan
Mobile Home Dealers
Carousels
Horse Racing
Boat Parts & Supplies
Hybrid Car Repair
Uzbek
Caricatures
Scandinavian
Skydiving
Spin Classes
Diamond Buyers
Process Servers
Aircraft Repairs
Tax Law
Concierge Medicine
Behavior Analysts
Whale Watching Tours
IP & Internet Law
Art Consultants
Art Installation
Holiday Decorating Services
Bail Bondsmen
Elevator Services
Public Adjusters
Silent Disco
Israeli
Sperm Clinic
Childproofing
Embassy
Golf Cart Rentals
Supper Clubs
First Aid Classes
Bookbinding
Community Gardens
Kiteboarding
Vermouth Bars
Hazardous Waste Disposal
Solar Panel Cleaning
Sledding
Sandblasting
Neuropathologists
Planetarium
Furniture Rental
Beer Hall
Veterans Organizations
Fur Clothing
Ziplining
Hang Gliding
Paragliding
Sex Therapists
Elder Care Planning
Georgian
Mortuary Services
Duplication Services
Disability Law
Sailing
Hepatologists
College Counseling
Aircraft Dealers
Nudist
Otologists
Fuzhou
Currency Exchange
Foot Care
Ferries
Senior Centers
Homeless Shelters
Traditional Clothing
Fire Departments
Outdoor Movies
Sport Equipment Hire
Fuel Docks
Teacher Supplies
Oxygen Bars
Osteopaths
Parklets
Town Hall
Bike Shop
3D Printing
Biohazard Cleanup
Neurotologists
Experiences
Apartment Agents
Hotel bar
Elder Law
Pathologists
Sheds & Outdoor Storage
Kiosk
Sports Psychologists
Luggage Storage
Bike Parking
Roman
Beach Bars
Bus Stations
Calligraphy
Contract Law
Hungarian
Hindu Temples
DUI Schools
Hakka
Consumer Law
Patent Law
Cannabis Tours
Bocce Ball
Scooter Tours
Housing Cooperatives
Guamanian
Cheese Tasting Classes
Tonkatsu
Donburi
Animal Assisted Therapy
Skiing
Pita
Vocal Coach
Eastern European
Sauna Installation & Repair
Interlock Systems
Mosques
Ice Delivery
Storefront Clinics
Metal Detector Services
Wildlife Hunting Ranges
Rodeo
Dumplings
Fencing Clubs
Cheerleading
Cucina campana
Dart Arenas
Circus Schools
Karaoke Rental
Halfway Houses
Mohels
Aviation Services
Conveyor Belt Sushi
Dialysis Clinics
Makerspaces
Natural Gas Suppliers
Hospitalists
Serbo Croatian
Ceremonial Clothing
Bubble Soccer
Trade Fairs

In [8]:
keywords = ['museum', 'park', 'Hotel', 'Motel', 'Hostel', 'restaurant', 'Restaurant', 'forest', 'gallery', 'mall', 'pub', 'Zoo', 'roller coaster']

keywords_lower = [keyword.lower() for keyword in keywords]

mask = rt_df['categories'].str.contains('|'.join(keywords))

filtered_dataframe = rt_df[mask]

filtered_dataframe

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 10, Finished, Available)

,business_id,name,address,city,state,latitude,longitude,stars,review_count,categories
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,Restaurants
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,40.338183,-75.471659,4.5,13,Brewpubs
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,AZ,36.269593,-87.058943,2.0,6,Restaurants
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,8025 Mackenzie Rd,Affton,TN,38.565165,-90.321087,3.0,19,Restaurants
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,MO,36.208102,-86.768170,1.5,10,Restaurants
...,...,...,...,...,...,...,...,...,...,...
150331,qQ7FHvkGEMqoPKKXPk4gjA,La Quinta by Wyndham NW Tucson Marana,6020 West Hospitality Rd,Tucson,AZ,32.358587,-111.093308,2.5,67,Hotels & Travel
150331,qQ7FHvkGEMqoPKKXPk4gjA,La Quinta by Wyndham NW Tucson Marana,6020 West Hospitality Rd,Tucson,AZ,32.358587,-111.093308,2.5,67,Hotels
150336,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,1108 S 9th St,Philadelphia,MO,39.935982,-75.158665,4.5,35,Restaurants
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4405 Pennell Rd,Aston,PA,39.856185,-75.427725,4.5,14,Restaurants
150340,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,NJ,53.509649,-113.675999,4.5,18,Restaurants

In [9]:
filtered_dataframe = ut.group_column(filtered_dataframe, 'categories')
filtered_dataframe

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 11, Finished, Available)

,business_id,name,address,city,state,latitude,longitude,stars,review_count,categories
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,[Restaurants]
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,40.338183,-75.471659,4.5,13,[Brewpubs]
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,AZ,36.269593,-87.058943,2.0,6,[Restaurants]
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,8025 Mackenzie Rd,Affton,TN,38.565165,-90.321087,3.0,19,[Restaurants]
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,MO,36.208102,-86.768170,1.5,10,[Restaurants]
...,...,...,...,...,...,...,...,...,...,...
150327,cM6V90ExQD6KMSU3rRB5ZA,Dutch Bros Coffee,1181 N Milwaukee St,Boise,ID,43.615401,-116.284689,4.0,33,[Restaurants]
150331,qQ7FHvkGEMqoPKKXPk4gjA,La Quinta by Wyndham NW Tucson Marana,6020 West Hospitality Rd,Tucson,AZ,32.358587,-111.093308,2.5,67,"[Hotels & Travel, Hotels]"
150336,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,1108 S 9th St,Philadelphia,MO,39.935982,-75.158665,4.5,35,[Restaurants]
150339,2O2K6SXPWv56amqxCECd4w,The Plum Pit,4405 Pennell Rd,Aston,PA,39.856185,-75.427725,4.5,14,[Restaurants]
150340,hn9Toz3s-Ei3uZPt7esExA,West Side Kebab House,2470 Guardian Road NW,Edmonton,NJ,53.509649,-113.675999,4.5,18,[Restaurants]

In [10]:
df1 = filtered_dataframe[['business_id', 'longitude', 'latitude']]
df1

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 12, Finished, Available)

                   business_id   longitude   latitude
3       MTSW4McQd7CbVtyjqoe9mw  -75.155564  39.955505
4       mWMc6_wTdE0EUBKIGXDVfA  -75.471659  40.338183
5       CF33F8-E6oudUQ46HnavjQ  -87.058943  36.269593
8       k0hlBqXX-Bt0vf1op7Jr1w  -90.321087  38.565165
9       bBDDEgkFA1Otx9Lfe7BZUQ  -86.768170  36.208102
...                        ...         ...        ...
150327  cM6V90ExQD6KMSU3rRB5ZA -116.284689  43.615401
150331  qQ7FHvkGEMqoPKKXPk4gjA -111.093308  32.358587
150336  WnT9NIzQgLlILjPT0kEcsQ  -75.158665  39.935982
150339  2O2K6SXPWv56amqxCECd4w  -75.427725  39.856185
150340  hn9Toz3s-Ei3uZPt7esExA -113.675999  53.509649

[57826 rows x 3 columns]

In [11]:
df1 = df1.drop_duplicates().reset_index(drop=True)
df1

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 13, Finished, Available)

                  business_id   longitude   latitude
0      MTSW4McQd7CbVtyjqoe9mw  -75.155564  39.955505
1      mWMc6_wTdE0EUBKIGXDVfA  -75.471659  40.338183
2      CF33F8-E6oudUQ46HnavjQ  -87.058943  36.269593
3      k0hlBqXX-Bt0vf1op7Jr1w  -90.321087  38.565165
4      bBDDEgkFA1Otx9Lfe7BZUQ  -86.768170  36.208102
...                       ...         ...        ...
57821  cM6V90ExQD6KMSU3rRB5ZA -116.284689  43.615401
57822  qQ7FHvkGEMqoPKKXPk4gjA -111.093308  32.358587
57823  WnT9NIzQgLlILjPT0kEcsQ  -75.158665  39.935982
57824  2O2K6SXPWv56amqxCECd4w  -75.427725  39.856185
57825  hn9Toz3s-Ei3uZPt7esExA -113.675999  53.509649

[57826 rows x 3 columns]

In [1]:
# Take the coordinates and assign the city where it is located using the API
file_location = '/lakehouse/default/Files/df_database/state.parquet'
api_key = 'AIzaSyAHo-DQhxRt2aCx1rHZHq9_4BpKQoGs'
df_state = ut.state_dataframe(df1, file_location, api_key)

StatementMeta(, , , SessionStarting, )

In [ ]:
df_state

StatementMeta(, , , Waiting, )

In [14]:
unique_states = df_state['State'].unique()

# Imprimir los valores únicos
print("Valores únicos en la columna 'State':")
print(unique_states)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 16, Finished, Available)

Valores únicos en la columna 'State':
['Pennsylvania' 'Tennessee' 'Missouri' 'Florida' 'Indiana' 'Louisiana'
 'Alberta' 'Nevada' 'Idaho' 'Illinois' 'Arizona' 'New Jersey' 'California'
 'Delaware' None 'NY' 'ME' 'TX' 'MD']

We filter by the states that are of interest to us

In [15]:
allowed_states = ['California', 'Florida', 'Nevada', 'Indiana', 'Lousiana', 'Illinois', 'New Jersey']

df_state = df_state[df_state['State'].isin(allowed_states)]
df_state

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 17, Finished, Available)

                  business_id   longitude   latitude       State
4      eEOYSgkmpB90uNA7lDOMRA  -82.456320  27.955269     Florida
5      il_Ro8jwPlHresjw9EGmBg  -86.127217  39.637133     Indiana
6      0bPLkL0QhhPO5kt1_EXmNQ  -82.760461  27.916116     Florida
11     kfNv-JZpuN6TVNSO6hHdkw  -86.053080  39.904320     Indiana
12     9OG5YkX1g2GReZM0AskizA -119.789339  39.476117      Nevada
...                       ...         ...        ...         ...
60870  -bZQH8yjm7ntTyGeLQwh8Q  -82.750395  27.916787     Florida
60872  BIyT7Kr7tMJqlfp4oOOYQg  -82.316887  27.853745     Florida
60873  8BUr8GviR2o_b-brO21wwQ -119.856886  34.412966  California
60883  uriD7RFuHhLJeDdKaf0nFA -119.739681  34.440689  California
60885  esBGrrmuZzSiECyRBoKvvA  -82.643069  27.770872     Florida

[23590 rows x 4 columns]

In [16]:
business = pd.merge(business, df_state, on=['business_id', 'longitude', 'latitude'], how = "inner")

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 18, Finished, Available)

In [17]:
business = business.drop(columns=['state'])

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 19, Finished, Available)

Having the Business dataframe without these columns makes it easier for us to manage the relevant information throughout this process.

___
#### 3.2 Checkin Dataframe

In [18]:
checkin.head()

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 20, Finished, Available)

              business_id                                               date
0  ---kPU91CF4Lq2-WlRu9Lw  2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020...
1  --0iUa4sNDFiZFrAdIWhZQ  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011...
2  --30_8IhuyMHbSOcNWd6DQ           2013-06-14 23:29:17, 2014-08-13 23:20:22
3  --7PUidqRWpRSpXebiyxTg  2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012...
4  --7jw19RH9JKXgFohspgQw  2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014...

In [19]:
checkin.info()

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 21, Finished, Available)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131930 entries, 0 to 131929
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   business_id  131930 non-null  object
 1   date         131930 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

###### The date-time combination is not useful for our purposes, so we proceed to count the number of those records per row.

In [20]:
def count_element (date):
    dates = date.split(",")
    return len(dates)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 22, Finished, Available)

In [21]:
checkin["count_checkin"] = checkin["date"].apply(count_element) 
checkin.drop(columns=['date'], inplace=True)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 23, Finished, Available)

In [22]:
checkin.head()

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 24, Finished, Available)

              business_id  count_checkin
0  ---kPU91CF4Lq2-WlRu9Lw             11
1  --0iUa4sNDFiZFrAdIWhZQ             10
2  --30_8IhuyMHbSOcNWd6DQ              2
3  --7PUidqRWpRSpXebiyxTg             10
4  --7jw19RH9JKXgFohspgQw             26

In this way we have information on the number of records that exist by business ID.

___
#### 3.3 Review Dataframe

We create a brief visualization to understand the information contained in the dataframe

In [23]:
review.head(2)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 25, Finished, Available)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18

In [24]:
ut.data_summ(review)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 26, Finished, Available)

     Column                                            Data_type  No_miss_Qty  %Missing  Missing_Qty
  review_id                                      [<class 'str'>]      6990280       0.0            0
    user_id                                      [<class 'str'>]      6990280       0.0            0
business_id                                      [<class 'str'>]      6990280       0.0            0
      stars                                      [<class 'int'>]      6990280       0.0            0
     useful                                      [<class 'int'>]      6990280       0.0            0
      funny                                      [<class 'int'>]      6990280       0.0            0
       cool                                      [<class 'int'>]      6990280       0.0            0
       text                                      [<class 'str'>]      6990280       0.0            0
       date [<class 'pandas._libs.tslibs.timestamps.Timestamp'>]      6990280       0.0            0
=====================================

,Column,Data_type,No_miss_Qty,%Missing,Missing_Qty
0,review_id,[<class 'str'>],6990280,0.0,0
1,user_id,[<class 'str'>],6990280,0.0,0
2,business_id,[<class 'str'>],6990280,0.0,0
3,stars,[<class 'int'>],6990280,0.0,0
4,useful,[<class 'int'>],6990280,0.0,0
5,funny,[<class 'int'>],6990280,0.0,0
6,cool,[<class 'int'>],6990280,0.0,0
7,text,[<class 'str'>],6990280,0.0,0
8,date,[<class 'pandas._libs.tslibs.timestamps.Timest...,6990280,0.0,0

In [25]:
review = review.drop(["review_id", "useful", "funny", "cool"], axis=1)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 27, Finished, Available)

The columns "review_id", "useful", "funny", "cool" and "date" which contain irrelevant content are removed from the dataframe

___
#### 3.4 Tip Dataframe

In [26]:
tip.head(2)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 28, Finished, Available)

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0

We can see the content of the Tip dataframe which has 6 columns:
- User id
- Business_id
- Text
- Date
- Compliment_count

The information contained in this dataframe is mainly to store tips or shorter reviews aimed at giving advice. This dataframe is irrelevant to us due to the fact that we have repeated information but more briefly about the review information.

___
#### 3.5 User Dataframe

In [27]:
user.head()

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 29, Finished, Available)

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,1,0,0,0,1,1,0,0,0,0

In [28]:
ut.data_summ(user)

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 30, Finished, Available)

            Column         Data_type  No_miss_Qty  %Missing  Missing_Qty
           user_id   [<class 'str'>]      2105597       0.0            0
              name   [<class 'str'>]      2105597       0.0            0
      review_count   [<class 'int'>]      2105597       0.0            0
     yelping_since   [<class 'str'>]      2105597       0.0            0
            useful   [<class 'int'>]      2105597       0.0            0
             funny   [<class 'int'>]      2105597       0.0            0
              cool   [<class 'int'>]      2105597       0.0            0
             elite   [<class 'str'>]      2105597       0.0            0
           friends   [<class 'str'>]      2105597       0.0            0
              fans   [<class 'int'>]      2105597       0.0            0
     average_stars [<class 'float'>]      2105597       0.0            0
    compliment_hot   [<class 'int'>]      2105597       0.0            0
   compliment_more   [<class 'int'>]      2105597       0.0            0
compliment_profile   [<class 'int'>]      2105597       0.0            0
   compliment_cute   [<class 'int'>]      2105597       0.0            0
   compliment_list   [<class 'int'>]      2105597       0.0            0
   compliment_note   [<class 'int'>]      2105597       0.0            0
  compliment_plain   [<class 'int'>]      2105597       0.0            0
   compliment_cool   [<class 'int'>]      2105597       0.0            0
  compliment_funny   [<class 'int'>]      2105597       0.0            0
 compliment_writer   [<class 'int'>]      2105597       0.0            0
 compliment_photos   [<class 'int'>]      2105597       0.0            0
=====================================

                Column          Data_type  No_miss_Qty  %Missing  Missing_Qty
0              user_id    [<class 'str'>]      2105597       0.0            0
1                 name    [<class 'str'>]      2105597       0.0            0
2         review_count    [<class 'int'>]      2105597       0.0            0
3        yelping_since    [<class 'str'>]      2105597       0.0            0
4               useful    [<class 'int'>]      2105597       0.0            0
5                funny    [<class 'int'>]      2105597       0.0            0
6                 cool    [<class 'int'>]      2105597       0.0            0
7                elite    [<class 'str'>]      2105597       0.0            0
8              friends    [<class 'str'>]      2105597       0.0            0
9                 fans    [<class 'int'>]      2105597       0.0            0
10       average_stars  [<class 'float'>]      2105597       0.0            0
11      compliment_hot    [<class 'int'>]      2105597       0.0            0
12     compliment_more    [<class 'int'>]      2105597       0.0            0
13  compliment_profile    [<class 'int'>]      2105597       0.0            0
14     compliment_cute    [<class 'int'>]      2105597       0.0            0
15     compliment_list    [<class 'int'>]      2105597       0.0            0
16     compliment_note    [<class 'int'>]      2105597       0.0            0
17    compliment_plain    [<class 'int'>]      2105597       0.0            0
18     compliment_cool    [<class 'int'>]      2105597       0.0            0
19    compliment_funny    [<class 'int'>]      2105597       0.0            0
20   compliment_writer    [<class 'int'>]      2105597       0.0            0
21   compliment_photos    [<class 'int'>]      2105597       0.0            0

We can see that we have this dataframe oriented to the information of the user who made the review, organized with 22 columns:

- user_id
- name   
- review_count   
- yelping_since   
- useful   
- funny   
- cool   
- elite   
- friends   
- fans   
- average_stars 
- compliment_hot   
- compliment_more   
- compliment_profile   
- compliment_cute   
- compliment_list   
- compliment_note   
- compliment_plain   
- compliment_cool   
- compliment_funny   
- compliment_writer   
- compliment_photos   

Most of these columns store quantities of elements that are not relevant to us.

In [29]:
user = user[['user_id', 'name']]

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 31, Finished, Available)

In this way we leave the User dataframe, with the only relevant columns that are 'user_id' and 'name', which store the user IDs and respective names.

___
### 4 - Unification of all information - YELP

##### Observations:
- the information provided in the Tip file has abbreviated user reviews. As the Review file contains more detailed information on comments and ratings from users, we proceeded to use it to unify the files and not use the Tip file.
- Tables are linked via business_id and user_id

A main dataframe is created which will unite the information from the dataframes:
Business, Review, Checkin and User

In [30]:
dy_df = pd.merge(business, checkin, on= "business_id")
dy_df = pd.merge(dy_df, review, on="business_id" )
dy_df = pd.merge(dy_df, user, on="user_id" )
dy_df

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 32, Finished, Available)

,business_id,name_x,address,city,latitude,longitude,stars_x,review_count,categories,State,count_checkin,user_id,stars_y,text,date,name_y
0,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,,Tampa Bay,27.955269,-82.456320,4.0,10,"[Vietnamese, Food, Restaurants, Food Trucks]",Florida,4,nnu9h6du4E6oqMasPgKR3Q,5,I eat pho about 4 times a week and from a spec...,2019-04-04 16:03:00,Dana
1,AODksDNj5mH953cyhUG1Qw,Thai 5 Fast Food,3424 S Dale Mabry Hwy,Tampa,27.912060,-82.505768,4.0,336,"[Laotian, American (Traditional), Asian Fusion...",Florida,495,nnu9h6du4E6oqMasPgKR3Q,1,Had gotten the Pad see eew in the past and did...,2018-02-04 18:25:53,Dana
2,F9D2mQ4u-D5i0EWrcI01DQ,Thai Gourmet Market,5831 Memorial Hwy,Tampa,27.984573,-82.568798,4.5,194,"[Event Planning & Services, Ethnic Food, Asian...",Florida,499,nnu9h6du4E6oqMasPgKR3Q,5,"BEST PAD Thai I have ever had!! Seriously, not...",2016-06-11 23:14:50,Dana
3,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,,Tampa Bay,27.955269,-82.456320,4.0,10,"[Vietnamese, Food, Restaurants, Food Trucks]",Florida,4,JlEdjZvhAbFCU-ObZQb1lw,5,I've been in Wesley Chapel area for about 2 ye...,2018-10-23 00:36:29,Linh
4,Wk21f0DAM7uj3DaJ_rMI-Q,Brunchies - Lutz,24400 State Rd 54,Lutz,28.185389,-82.413001,4.0,272,"[Restaurants, Breakfast & Brunch, Coffee & Tea...",Florida,298,JlEdjZvhAbFCU-ObZQb1lw,5,My experience was wonderful. My server Michea...,2018-01-13 20:08:35,Linh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2516649,esBGrrmuZzSiECyRBoKvvA,Colony Grill - St. Petersburg,670 Central Ave,St. Petersburg,27.770872,-82.643069,4.5,38,"[Bars, Beer Bar, Nightlife, Wine Bars, Pizza, ...",Florida,20,V0vxjcA66r80_nZsTyCg8Q,5,"We are from Connecticut, so expectations were ...",2021-11-12 22:04:25,Barbara
2516650,esBGrrmuZzSiECyRBoKvvA,Colony Grill - St. Petersburg,670 Central Ave,St. Petersburg,27.770872,-82.643069,4.5,38,"[Bars, Beer Bar, Nightlife, Wine Bars, Pizza, ...",Florida,20,NmJ6gpoLY6WGNJkk6jA8Zg,1,You would think that a restaurant called Colon...,2021-11-10 13:21:11,Elizabeth
2516651,esBGrrmuZzSiECyRBoKvvA,Colony Grill - St. Petersburg,670 Central Ave,St. Petersburg,27.770872,-82.643069,4.5,38,"[Bars, Beer Bar, Nightlife, Wine Bars, Pizza, ...",Florida,20,l-Kwk2mDOwEBXG8X5sU6lw,5,Ive been coming to Colony Grille in CT for ove...,2021-11-03 19:28:06,Paul From Norwalk
2516652,esBGrrmuZzSiECyRBoKvvA,Colony Grill - St. Petersburg,670 Central Ave,St. Petersburg,27.770872,-82.643069,4.5,38,"[Bars, Beer Bar, Nightlife, Wine Bars, Pizza, ...",Florida,20,QGMX1H6WQTp-o8Qq3uO3dQ,5,Colony Grill occupies one of the larger eatery...,2021-12-27 19:56:12,William
2516653,esBGrrmuZzSiECyRBoKvvA,Colony Grill - St. Petersburg,670 Central Ave,St. Petersburg,27.770872,-82.643069,4.5,38,"[Bars, Beer Bar, Nightlife, Wine Bars, Pizza, ...",Florida,20,rDtA_KBbjnPjsKDT0-itgA,5,The pizza was thin crust and light. Great spot...,2021-11-14 16:53:07,Boxer

In [31]:
Yelp = dy_df[["name_x", "address", "city", "State", "latitude", "longitude", "stars_x", "review_count", "date", "count_checkin", "user_id", "stars_y", "text", "name_y", "categories"]]

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 33, Finished, Available)

In [32]:
Yelp = Yelp.rename(columns={
    "name_x": 'Business_Name',
    "address": 'Address',
    "city": 'City',
    "state": 'State',
    "latitude": 'Latitude',
    "longitude": 'Longitude',
    "stars_x": 'Ranking',
    "review_count": 'Review_Count',
    "date" : "Date",
    "count_checkin": 'Checkin_Count',
    "user_id": 'User_Id',
    "stars_y": 'Stars',
    "text": 'Text',
    "name_y": 'User_Name',
    "categories": 'Category'
})

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 34, Finished, Available)

Once the Dataframe has been filtered and regrouped, we end up generating a parquet file which contains all the filtered information separated into the columns:
- 'Business_Name',
- 'Address',
- 'City',
- 'State',
- 'Latitude',
- 'Longitude',
- 'Ranking',
- 'Review_Count',
- 'Checkin_Count',
- 'User_Id',
- 'Stars',
- 'Text',
- 'User_Name',
- 'Category’

In [33]:
Yelp

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 35, Finished, Available)

,Business_Name,Address,City,State,Latitude,Longitude,Ranking,Review_Count,Date,Checkin_Count,User_Id,Stars,Text,User_Name,Category
0,Vietnamese Food Truck,,Tampa Bay,Florida,27.955269,-82.456320,4.0,10,2019-04-04 16:03:00,4,nnu9h6du4E6oqMasPgKR3Q,5,I eat pho about 4 times a week and from a spec...,Dana,"[Vietnamese, Food, Restaurants, Food Trucks]"
1,Thai 5 Fast Food,3424 S Dale Mabry Hwy,Tampa,Florida,27.912060,-82.505768,4.0,336,2018-02-04 18:25:53,495,nnu9h6du4E6oqMasPgKR3Q,1,Had gotten the Pad see eew in the past and did...,Dana,"[Laotian, American (Traditional), Asian Fusion..."
2,Thai Gourmet Market,5831 Memorial Hwy,Tampa,Florida,27.984573,-82.568798,4.5,194,2016-06-11 23:14:50,499,nnu9h6du4E6oqMasPgKR3Q,5,"BEST PAD Thai I have ever had!! Seriously, not...",Dana,"[Event Planning & Services, Ethnic Food, Asian..."
3,Vietnamese Food Truck,,Tampa Bay,Florida,27.955269,-82.456320,4.0,10,2018-10-23 00:36:29,4,JlEdjZvhAbFCU-ObZQb1lw,5,I've been in Wesley Chapel area for about 2 ye...,Linh,"[Vietnamese, Food, Restaurants, Food Trucks]"
4,Brunchies - Lutz,24400 State Rd 54,Lutz,Florida,28.185389,-82.413001,4.0,272,2018-01-13 20:08:35,298,JlEdjZvhAbFCU-ObZQb1lw,5,My experience was wonderful. My server Michea...,Linh,"[Restaurants, Breakfast & Brunch, Coffee & Tea..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2516649,Colony Grill - St. Petersburg,670 Central Ave,St. Petersburg,Florida,27.770872,-82.643069,4.5,38,2021-11-12 22:04:25,20,V0vxjcA66r80_nZsTyCg8Q,5,"We are from Connecticut, so expectations were ...",Barbara,"[Bars, Beer Bar, Nightlife, Wine Bars, Pizza, ..."
2516650,Colony Grill - St. Petersburg,670 Central Ave,St. Petersburg,Florida,27.770872,-82.643069,4.5,38,2021-11-10 13:21:11,20,NmJ6gpoLY6WGNJkk6jA8Zg,1,You would think that a restaurant called Colon...,Elizabeth,"[Bars, Beer Bar, Nightlife, Wine Bars, Pizza, ..."
2516651,Colony Grill - St. Petersburg,670 Central Ave,St. Petersburg,Florida,27.770872,-82.643069,4.5,38,2021-11-03 19:28:06,20,l-Kwk2mDOwEBXG8X5sU6lw,5,Ive been coming to Colony Grille in CT for ove...,Paul From Norwalk,"[Bars, Beer Bar, Nightlife, Wine Bars, Pizza, ..."
2516652,Colony Grill - St. Petersburg,670 Central Ave,St. Petersburg,Florida,27.770872,-82.643069,4.5,38,2021-12-27 19:56:12,20,QGMX1H6WQTp-o8Qq3uO3dQ,5,Colony Grill occupies one of the larger eatery...,William,"[Bars, Beer Bar, Nightlife, Wine Bars, Pizza, ..."
2516653,Colony Grill - St. Petersburg,670 Central Ave,St. Petersburg,Florida,27.770872,-82.643069,4.5,38,2021-11-14 16:53:07,20,rDtA_KBbjnPjsKDT0-itgA,5,The pizza was thin crust and light. Great spot...,Boxer,"[Bars, Beer Bar, Nightlife, Wine Bars, Pizza, ..."

In [34]:
Yelp.to_parquet('/lakehouse/default/Files/df_database/files_to_EDA/Yelp_to_EDA.parquet')

StatementMeta(, 3c52b027-0896-4fe6-9576-75033c0ca337, 36, Finished, Available)