### 1- IMPORT LIBRARIES

In [1]:
import builtin.utils as ut
import pandas as pd
from ast import literal_eval
import ast

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 3, Finished, Available)

___
### 2- LOAD CLEAN DATA

Guardamos en variables las rutas correspondientes a la ubicación de la data

In [2]:
yelp_bus = '/lakehouse/default/Files/df_database/Yelp_parquet/business.pkl.parquet'
yelp_check = '/lakehouse/default/Files/df_database/Yelp_parquet/checkin.json.parquet'
yelp_review = '/lakehouse/default/Files/df_database/Yelp_parquet/review.json.parquet'
yelp_tip = '/lakehouse/default/Files/df_database/Yelp_parquet/tip.json.parquet'
yelp_user = '/lakehouse/default/Files/df_database/Yelp_parquet/user.parquet'

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 4, Finished, Available)

Se carga el contenido de cada ruta utilizando Pandas, almacenando el contenido como dataframes en diferentes variables

In [3]:
business = pd.read_parquet(yelp_bus)
checkin = pd.read_parquet(yelp_check)
review = pd.read_parquet(yelp_review)
tip = pd.read_parquet(yelp_tip)
user = pd.read_parquet(yelp_user)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 5, Finished, Available)

Tenemos ahora 5 dataframes diferentes, con la información correspondiente a los archivos brindados por YELP.
Dataframes:
- Business
- Checkin
- Review
- Tip
- User

___
### 3 - TRANSFORM

#### 3.1 Business Dataframe

In [4]:
business.head()

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 6, Finished, Available)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,None,93101,34.426679,-119.711197,5.0,7,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,None,63123,38.551126,-90.335695,3.0,15,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Shipping Centers, Local Services, Notaries, Ma...","{'Friday': '8:0-18:30', 'Monday': '0:0-0:0', '..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,None,85711,32.223236,-110.880452,3.5,22,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Department Stores, Shopping, Fashion, Home & G...","{'Friday': '8:0-23:0', 'Monday': '8:0-22:0', '..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,19107,39.955505,-75.155564,4.0,80,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Friday': '7:0-21:0', 'Monday': '7:0-20:0', '..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,18054,40.338183,-75.471659,4.5,13,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Brewpubs, Breweries, Food","{'Friday': '12:0-22:0', 'Monday': None, 'Satur..."

In [5]:
ut.data_summ(business)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 7, Finished, Available)

      Column                            Data_type  No_miss_Qty  %Missing  Missing_Qty
 business_id                      [<class 'str'>]       150346      0.00            0
        name                      [<class 'str'>]       150346      0.00            0
     address                      [<class 'str'>]       150346      0.00            0
        city                      [<class 'str'>]       150346      0.00            0
       state  [<class 'NoneType'>, <class 'str'>]       150343      0.00            3
 postal_code                      [<class 'str'>]       150346      0.00            0
    latitude                    [<class 'float'>]       150346      0.00            0
   longitude                    [<class 'float'>]       150346      0.00            0
       stars                    [<class 'float'>]       150346      0.00            0
review_count                      [<class 'int'>]       150346      0.00            0
     is_open                      [<class 'int'>]       150346      0.00            0
  attributes [<class 'dict'>, <class 'NoneType'>]       136602      9.14        13744
  categories  [<class 'str'>, <class 'NoneType'>]       150243      0.07          103
       hours [<class 'NoneType'>, <class 'dict'>]       127123     15.45        23223
=====================================

,Column,Data_type,No_miss_Qty,%Missing,Missing_Qty
0,business_id,[<class 'str'>],150346,0.00,0
1,name,[<class 'str'>],150346,0.00,0
2,address,[<class 'str'>],150346,0.00,0
3,city,[<class 'str'>],150346,0.00,0
4,state,"[<class 'NoneType'>, <class 'str'>]",150343,0.00,3
5,postal_code,[<class 'str'>],150346,0.00,0
6,latitude,[<class 'float'>],150346,0.00,0
7,longitude,[<class 'float'>],150346,0.00,0
8,stars,[<class 'float'>],150346,0.00,0
9,review_count,[<class 'int'>],150346,0.00,0
10,is_open,[<class 'int'>],150346,0.00,0
11,attributes,"[<class 'dict'>, <class 'NoneType'>]",136602,9.14,13744
12,categories,"[<class 'str'>, <class 'NoneType'>]",150243,0.07,103
13,hours,"[<class 'NoneType'>, <class 'dict'>]",127123,15.45,23223


Se observa el contenido ~*head*~ del dataframe, el cuenta con 14 columnas con la información de:

- **Businnes ID**:    Contiene STR de identificación del negocio
- **Name**:    STR Contiene el nombre del negocio
- **Address**:    STR Contiene la dirección completa del negocio
- **City**:    STR    Contiene la ciudad donde está ubicado el negocio
- **State**:    STR Contiene el estado donde está ubicado el negocio
- **Postal Code**:    STR Contiene el código postal de la ubicación del negocio
- **Latitude**:    Float Contiene la Latitud
- **Longitude**:    Float Contiene la Longitud
- **Is Open**:    INT Contiene 1 y 0 para indicar si el negocio está abierto o está cerrado respectivamente. 
- **Stars**:    Float Contiene la cantidad de estrellas, entre 0 y 5
- **Review_count**:    Int Contiene el recuento de reviews del negocio
- **Attributes**:    STR contiene atributos del negocio como valores
- **Categories**:    Contiene las categorías del negocio
- **Hours**:    STR Contiene el horario en que se encuentra abierto

Para la propuesta del proyecto que estamos llevando a cabo, varias de las columnas son relevantes como tambien otras no lo son. <br>
Por lo tanto, procedemos a eliminar aquellas columnas que no nos son relevantes, entre ellas: "Postal_code", "is_open", "attributes", "hours"

In [6]:
business = business.drop(["postal_code", "is_open", "attributes", "hours"], axis=1)
business

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 8, Finished, Available)

,business_id,name,address,city,state,latitude,longitude,stars,review_count,categories
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,None,34.426679,-119.711197,5.0,7,"Doctors, Traditional Chinese Medicine, Naturop..."
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,None,38.551126,-90.335695,3.0,15,"Shipping Centers, Local Services, Notaries, Ma..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,None,32.223236,-110.880452,3.5,22,"Department Stores, Shopping, Fashion, Home & G..."
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B..."
4,mWMc6_wTdE0EUBKIGXDVfA,Perkiomen Valley Brewery,101 Walnut St,Green Lane,MO,40.338183,-75.471659,4.5,13,"Brewpubs, Breweries, Food"
...,...,...,...,...,...,...,...,...,...,...
150341,IUQopTMmYQG-qRtBk-8QnA,Binh's Nails,3388 Gateway Blvd,Edmonton,IN,53.468419,-113.492054,3.0,13,"Nail Salons, Beauty & Spas"
150342,c8GjPIOTGVmIemT7j5_SyQ,Wild Birds Unlimited,2813 Bransford Ave,Nashville,DE,36.115118,-86.766925,4.0,5,"Pets, Nurseries & Gardening, Pet Stores, Hobby..."
150343,_QAMST-NrQobXduilWEqSw,Claire's Boutique,"6020 E 82nd St, Ste 46",Indianapolis,AB,39.908707,-86.065088,3.5,8,"Shopping, Jewelry, Piercing, Toy Stores, Beaut..."
150344,mtGm22y5c2UHNXDFAjaPNw,Cyclery & Fitness Center,2472 Troy Rd,Edwardsville,AB,38.782351,-89.950558,4.0,24,"Fitness/Exercise Equipment, Eyewear & Optician..."
150345,jV_XOycEzSlTx-65W906pg,Sic Ink,238 Apollo Beach Blvd,Apollo beach,TN,27.771002,-82.394910,4.5,9,"Beauty & Spas, Permanent Makeup, Piercing, Tattoo"

In [7]:
unique_states = business['state'].unique()
unique_states_list = list(unique_states)
print(unique_states_list)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 9, Finished, Available)

[None, 'CA', 'MO', 'AZ', 'PA', 'TN', 'FL', 'IN', 'LA', 'AB', 'NV', 'ID', 'DE', 'IL', 'NJ', 'NC', 'CO', 'WA', 'HI', 'UT', 'TX', 'MT', 'MI', 'SD', 'XMS', 'MA', 'VI', 'VT']

Filtramos por los estados que son de nuetsro interés

In [8]:
allowed_states = ['CA', 'FL', 'NY', 'NV', 'IN', 'MA', 'IL', 'DC', 'LA', 'HI', 'SC']

# Filtrar el DataFrame
business = business[business['state'].isin(allowed_states)]

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 10, Finished, Available)

Teniendo el dataframe Business sin estas columnas nos facilita el manejo de la información relevante a lo largo de este proceso

___
#### 3.2 Checkin Dataframe

In [9]:
checkin.head()

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 11, Finished, Available)

              business_id                                               date
0  ---kPU91CF4Lq2-WlRu9Lw  2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020...
1  --0iUa4sNDFiZFrAdIWhZQ  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011...
2  --30_8IhuyMHbSOcNWd6DQ           2013-06-14 23:29:17, 2014-08-13 23:20:22
3  --7PUidqRWpRSpXebiyxTg  2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012...
4  --7jw19RH9JKXgFohspgQw  2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014...

In [10]:
checkin.info()

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 12, Finished, Available)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131930 entries, 0 to 131929
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   business_id  131930 non-null  object
 1   date         131930 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

###### La combinación fecha-hora no nos resulta útil para nuestros fines, por lo que procedemos a realizar un conteo en la cantidad de esos registros que tiene por fila.

In [11]:
## Definimos una función que cuente la cantidad de regitros
def count_element (date):
    dates = date.split(",")
    return len(dates)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 13, Finished, Available)

In [12]:
checkin["count_checkin"] = checkin["date"].apply(count_element) 
checkin.drop(columns=['date'], inplace=True)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 14, Finished, Available)

In [13]:
checkin.head()

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 15, Finished, Available)

              business_id  count_checkin
0  ---kPU91CF4Lq2-WlRu9Lw             11
1  --0iUa4sNDFiZFrAdIWhZQ             10
2  --30_8IhuyMHbSOcNWd6DQ              2
3  --7PUidqRWpRSpXebiyxTg             10
4  --7jw19RH9JKXgFohspgQw             26

De esta manera contamos con la informacion de la cantidad de registros que existe por id de negocio

___
#### 3.3 Review Dataframe

Creamos una visualización breve para entender la información que contiene el dataframe

In [14]:
review.head(2)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 16, Finished, Available)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18

In [15]:
ut.data_summ(review)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 17, Finished, Available)

     Column                                            Data_type  No_miss_Qty  %Missing  Missing_Qty
  review_id                                      [<class 'str'>]      6990280       0.0            0
    user_id                                      [<class 'str'>]      6990280       0.0            0
business_id                                      [<class 'str'>]      6990280       0.0            0
      stars                                      [<class 'int'>]      6990280       0.0            0
     useful                                      [<class 'int'>]      6990280       0.0            0
      funny                                      [<class 'int'>]      6990280       0.0            0
       cool                                      [<class 'int'>]      6990280       0.0            0
       text                                      [<class 'str'>]      6990280       0.0            0
       date [<class 'pandas._libs.tslibs.timestamps.Timestamp'>]      6990280       0.0            0
=====================================

,Column,Data_type,No_miss_Qty,%Missing,Missing_Qty
0,review_id,[<class 'str'>],6990280,0.0,0
1,user_id,[<class 'str'>],6990280,0.0,0
2,business_id,[<class 'str'>],6990280,0.0,0
3,stars,[<class 'int'>],6990280,0.0,0
4,useful,[<class 'int'>],6990280,0.0,0
5,funny,[<class 'int'>],6990280,0.0,0
6,cool,[<class 'int'>],6990280,0.0,0
7,text,[<class 'str'>],6990280,0.0,0
8,date,[<class 'pandas._libs.tslibs.timestamps.Timest...,6990280,0.0,0

In [16]:
review = review.drop(["review_id", "useful", "funny", "cool"], axis=1)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 18, Finished, Available)

Se sacan del dataframe las columnas "review_id", "useful", "funny", "cool" y "date" las cuales contienen contenido irrelevante

___
#### 3.4 Tip Dataframe

In [17]:
tip.head(2)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 19, Finished, Available)

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0

Se puede observar el contenido del dataframe Tip el cual tiene 6 columnas
- User id
- Business_id
- Text
- Date
- Compliment_count

La informacion que contiene este dataframe es principalmente para almacenar tip o reseñas mas breves orientadas a dar consejos. Este dataframe nos resulta irrelevante por el hecho de tener informacion repetida pero mas brevemente de la informacion de reviews

___
#### 3.5 User Dataframe

In [18]:
user.head()

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 20, Finished, Available)

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,1,0,0,0,1,1,0,0,0,0

In [19]:
ut.data_summ(user)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 21, Finished, Available)

            Column         Data_type  No_miss_Qty  %Missing  Missing_Qty
           user_id   [<class 'str'>]      2105597       0.0            0
              name   [<class 'str'>]      2105597       0.0            0
      review_count   [<class 'int'>]      2105597       0.0            0
     yelping_since   [<class 'str'>]      2105597       0.0            0
            useful   [<class 'int'>]      2105597       0.0            0
             funny   [<class 'int'>]      2105597       0.0            0
              cool   [<class 'int'>]      2105597       0.0            0
             elite   [<class 'str'>]      2105597       0.0            0
           friends   [<class 'str'>]      2105597       0.0            0
              fans   [<class 'int'>]      2105597       0.0            0
     average_stars [<class 'float'>]      2105597       0.0            0
    compliment_hot   [<class 'int'>]      2105597       0.0            0
   compliment_more   [<class 'int'>]      2105597       0.0            0
compliment_profile   [<class 'int'>]      2105597       0.0            0
   compliment_cute   [<class 'int'>]      2105597       0.0            0
   compliment_list   [<class 'int'>]      2105597       0.0            0
   compliment_note   [<class 'int'>]      2105597       0.0            0
  compliment_plain   [<class 'int'>]      2105597       0.0            0
   compliment_cool   [<class 'int'>]      2105597       0.0            0
  compliment_funny   [<class 'int'>]      2105597       0.0            0
 compliment_writer   [<class 'int'>]      2105597       0.0            0
 compliment_photos   [<class 'int'>]      2105597       0.0            0
=====================================

                Column          Data_type  No_miss_Qty  %Missing  Missing_Qty
0              user_id    [<class 'str'>]      2105597       0.0            0
1                 name    [<class 'str'>]      2105597       0.0            0
2         review_count    [<class 'int'>]      2105597       0.0            0
3        yelping_since    [<class 'str'>]      2105597       0.0            0
4               useful    [<class 'int'>]      2105597       0.0            0
5                funny    [<class 'int'>]      2105597       0.0            0
6                 cool    [<class 'int'>]      2105597       0.0            0
7                elite    [<class 'str'>]      2105597       0.0            0
8              friends    [<class 'str'>]      2105597       0.0            0
9                 fans    [<class 'int'>]      2105597       0.0            0
10       average_stars  [<class 'float'>]      2105597       0.0            0
11      compliment_hot    [<class 'int'>]      2105597       0.0            0
12     compliment_more    [<class 'int'>]      2105597       0.0            0
13  compliment_profile    [<class 'int'>]      2105597       0.0            0
14     compliment_cute    [<class 'int'>]      2105597       0.0            0
15     compliment_list    [<class 'int'>]      2105597       0.0            0
16     compliment_note    [<class 'int'>]      2105597       0.0            0
17    compliment_plain    [<class 'int'>]      2105597       0.0            0
18     compliment_cool    [<class 'int'>]      2105597       0.0            0
19    compliment_funny    [<class 'int'>]      2105597       0.0            0
20   compliment_writer    [<class 'int'>]      2105597       0.0            0
21   compliment_photos    [<class 'int'>]      2105597       0.0            0

Se puede ver que tenemos este dataframe orientado a la informacion del usuario que haya hecho la review, organizado con 22 columnas:

- user_id
- name   
- review_count   
- yelping_since   
- useful   
- funny   
- cool   
- elite   
- friends   
- fans   
- average_stars 
- compliment_hot   
- compliment_more   
- compliment_profile   
- compliment_cute   
- compliment_list   
- compliment_note   
- compliment_plain   
- compliment_cool   
- compliment_funny   
- compliment_writer   
- compliment_photos   

La mayoría de éstas columnas guardan cantidades de elementos que no nos son relevantes

In [20]:
user = user[['user_id', 'name']]

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 22, Finished, Available)

De esta forma dejamos al dataframe User, con las unicas columnas relevantes que son 'user_id' y 'name', las cuales almacenan los id de usuarios y respectivos nombres

___
### 4 - Unificación de la información - YELP

##### Observaciones:
- la información proporcionada en el archivo Tip tiene reseñas abreviadas de los usuarios. Como el archivo Review contiene información mas detallada de los comentarios y puntuaciones por parte de los usuarios, procedimos a utilizar la misma para unificar los archivos y no usar el archivo Tip.
- Las tablas se vinculan a través de business_id y user_id

Se crea un dataframe principal el cual va a unir la informacion de los dataframes:
Business, Review, Checkin y User

In [21]:
dy_df = pd.merge(business, checkin, on= "business_id")
dy_df = pd.merge(dy_df, review, on="business_id" )
dy_df = pd.merge(dy_df, user, on="user_id" )
dy_df

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 23, Finished, Available)

,business_id,name_x,address,city,state,latitude,longitude,stars_x,review_count,categories,count_checkin,user_id,stars_y,text,date,name_y
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",335,6_SpY41LIHZuIaiDs5FMKA,4,This is nice little Chinese bakery in the hear...,2014-05-26 01:09:53,K
1,i_sAh-ylmOwCQmqRmXox8g,Monsú,901 Christian St,Philadelphia,IN,39.939138,-75.157907,4.0,309,"Italian, Restaurants, Gluten-Free",292,6_SpY41LIHZuIaiDs5FMKA,2,Had a mediocre late-lunch here on a Saturday a...,2014-12-04 07:03:34,K
2,9Qe5ib0bCgRITjYn-iA-Bg,Legal Sea Foods,8500 Essington Ave,Philadelphia,FL,39.876009,-75.242965,4.0,326,"Nightlife, Food, Beer, Wine & Spirits, Restaur...",1335,6_SpY41LIHZuIaiDs5FMKA,2,Among the different Legal Sea Foods restaurant...,2014-12-04 07:12:51,K
3,tMtI6ECD6hwM-nFp2kXLKQ,Tea Do,132 N 10th St,Philadelphia,IL,39.954605,-75.156209,4.0,835,"Juice Bars & Smoothies, Bubble Tea, Food, Coff...",4461,6_SpY41LIHZuIaiDs5FMKA,3,They have a cool shaking machine for making mi...,2014-12-04 07:17:19,K
4,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",335,tCXElwhzekJEH6QJe3xs7Q,4,This is the bakery I usually go to in Chinatow...,2013-10-05 15:19:06,Rob
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3803959,fn3ybdsRSrIDpKZTsRuAWg,INSPcenter/Thai Clinical Massage,"2625 N Meridian St, Unit 50",Indianapolis,IN,39.805057,-86.155975,4.0,12,"Massage Therapy, Rolfing, Beauty & Spas, Refle...",2,aWk0aW8zRdzoZ2O6K1KByA,5,I saw Joyce the first time via a groupon and I...,2014-08-05 21:24:44,Katie
3803960,fn3ybdsRSrIDpKZTsRuAWg,INSPcenter/Thai Clinical Massage,"2625 N Meridian St, Unit 50",Indianapolis,IN,39.805057,-86.155975,4.0,12,"Massage Therapy, Rolfing, Beauty & Spas, Refle...",2,IYTGm-0_7SSgwVBIxWsCNQ,5,"Joyce is my massage therapist, she uses massag...",2013-02-17 22:12:58,Heather
3803961,fn3ybdsRSrIDpKZTsRuAWg,INSPcenter/Thai Clinical Massage,"2625 N Meridian St, Unit 50",Indianapolis,IN,39.805057,-86.155975,4.0,12,"Massage Therapy, Rolfing, Beauty & Spas, Refle...",2,AQG8O2Xq-_Y0uvFEOrMrCQ,5,First timer at Thai massage. Experience was gr...,2019-06-12 18:09:33,Deji
3803962,fn3ybdsRSrIDpKZTsRuAWg,INSPcenter/Thai Clinical Massage,"2625 N Meridian St, Unit 50",Indianapolis,IN,39.805057,-86.155975,4.0,12,"Massage Therapy, Rolfing, Beauty & Spas, Refle...",2,wh2kDQuoB1bhLtdzgERdug,1,Can I choose a negative star rating?\nSCAM !!!...,2020-11-17 19:24:03,Jennie
3803963,fn3ybdsRSrIDpKZTsRuAWg,INSPcenter/Thai Clinical Massage,"2625 N Meridian St, Unit 50",Indianapolis,IN,39.805057,-86.155975,4.0,12,"Massage Therapy, Rolfing, Beauty & Spas, Refle...",2,t-LeOrYsf8jgWi9hB3o0zg,5,The best clinical massage that I have ever had...,2013-03-26 23:30:40,Reina

Una vez tenemos todo el conjunto de informacion unido en un dataframe, hacemos las modificaciones necesarias:

In [22]:
# Eliminar filas duplicadas
dy_df = dy_df.drop_duplicates().reset_index(drop = True)
dy_df

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 24, Finished, Available)

,business_id,name_x,address,city,state,latitude,longitude,stars_x,review_count,categories,count_checkin,user_id,stars_y,text,date,name_y
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",335,6_SpY41LIHZuIaiDs5FMKA,4,This is nice little Chinese bakery in the hear...,2014-05-26 01:09:53,K
1,i_sAh-ylmOwCQmqRmXox8g,Monsú,901 Christian St,Philadelphia,IN,39.939138,-75.157907,4.0,309,"Italian, Restaurants, Gluten-Free",292,6_SpY41LIHZuIaiDs5FMKA,2,Had a mediocre late-lunch here on a Saturday a...,2014-12-04 07:03:34,K
2,9Qe5ib0bCgRITjYn-iA-Bg,Legal Sea Foods,8500 Essington Ave,Philadelphia,FL,39.876009,-75.242965,4.0,326,"Nightlife, Food, Beer, Wine & Spirits, Restaur...",1335,6_SpY41LIHZuIaiDs5FMKA,2,Among the different Legal Sea Foods restaurant...,2014-12-04 07:12:51,K
3,tMtI6ECD6hwM-nFp2kXLKQ,Tea Do,132 N 10th St,Philadelphia,IL,39.954605,-75.156209,4.0,835,"Juice Bars & Smoothies, Bubble Tea, Food, Coff...",4461,6_SpY41LIHZuIaiDs5FMKA,3,They have a cool shaking machine for making mi...,2014-12-04 07:17:19,K
4,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",335,tCXElwhzekJEH6QJe3xs7Q,4,This is the bakery I usually go to in Chinatow...,2013-10-05 15:19:06,Rob
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2802881,fn3ybdsRSrIDpKZTsRuAWg,INSPcenter/Thai Clinical Massage,"2625 N Meridian St, Unit 50",Indianapolis,IN,39.805057,-86.155975,4.0,12,"Massage Therapy, Rolfing, Beauty & Spas, Refle...",2,aWk0aW8zRdzoZ2O6K1KByA,5,I saw Joyce the first time via a groupon and I...,2014-08-05 21:24:44,Katie
2802882,fn3ybdsRSrIDpKZTsRuAWg,INSPcenter/Thai Clinical Massage,"2625 N Meridian St, Unit 50",Indianapolis,IN,39.805057,-86.155975,4.0,12,"Massage Therapy, Rolfing, Beauty & Spas, Refle...",2,IYTGm-0_7SSgwVBIxWsCNQ,5,"Joyce is my massage therapist, she uses massag...",2013-02-17 22:12:58,Heather
2802883,fn3ybdsRSrIDpKZTsRuAWg,INSPcenter/Thai Clinical Massage,"2625 N Meridian St, Unit 50",Indianapolis,IN,39.805057,-86.155975,4.0,12,"Massage Therapy, Rolfing, Beauty & Spas, Refle...",2,AQG8O2Xq-_Y0uvFEOrMrCQ,5,First timer at Thai massage. Experience was gr...,2019-06-12 18:09:33,Deji
2802884,fn3ybdsRSrIDpKZTsRuAWg,INSPcenter/Thai Clinical Massage,"2625 N Meridian St, Unit 50",Indianapolis,IN,39.805057,-86.155975,4.0,12,"Massage Therapy, Rolfing, Beauty & Spas, Refle...",2,wh2kDQuoB1bhLtdzgERdug,1,Can I choose a negative star rating?\nSCAM !!!...,2020-11-17 19:24:03,Jennie
2802885,fn3ybdsRSrIDpKZTsRuAWg,INSPcenter/Thai Clinical Massage,"2625 N Meridian St, Unit 50",Indianapolis,IN,39.805057,-86.155975,4.0,12,"Massage Therapy, Rolfing, Beauty & Spas, Refle...",2,t-LeOrYsf8jgWi9hB3o0zg,5,The best clinical massage that I have ever had...,2013-03-26 23:30:40,Reina

###### Necesitamos hacer un tratamiento con respecto a la información correspondiente a la columna "categories", desanidar la información que contiene y filtrar aquellos de nuestro interés ( negocios ya filtrados en datos correspondientes a Google Maps)

In [23]:
# Convertir los datos str de la columna categories en lista real
dy_df["categories"] = dy_df["categories"].apply(lambda x: x.split(', ') if pd.notna(x) else [])

# Desanidado de datos que contiene la columna "categories"
rt_df = ut.explode_column(dy_df, "categories")

# Reemplazar valores nulos
rt_df = ut.replace_all_nulls(rt_df)

# Visualizar todas las categorias desanidadas
unique_categories = rt_df['categories'].unique()
for category in unique_categories:
    print(category)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 25, Finished, Available)

Restaurants
Food
Bubble Tea
Coffee & Tea
Bakeries
Italian
Gluten-Free
Nightlife
Beer
Wine & Spirits
Breakfast & Brunch
Bars
American (New)
Seafood
Juice Bars & Smoothies
Whiskey Bars
Burgers
Vietnamese
Sandwiches
Local Flavor
Food Stands
Gastropubs
Pubs
Food Trucks
Mexican
Korean
German
Grocery
Convenience Stores
Belgian
American (Traditional)
Noodles
Dim Sum
Hong Kong Style Cafe
Cantonese
Barbeque
Chinese
Vegetarian
Mediterranean
Szechuan
Soup
Ethiopian
Ethnic Food
Specialty Food
Vegan
Ice Cream & Frozen Yogurt
Desserts
Cambodian
Sushi Bars
Buffets
Asian Fusion
Japanese
Event Planning & Services
Caterers
Lounges
Steakhouses
Diners
Day Spas
Beauty & Spas
Hair Removal
Waxing
Skin Care
French
Comfort Food
Indian
Salad
Shanghainese
Tea Rooms
Thai
Delis
Pakistani
Hot Dogs
Cafes
Fast Food
Food Delivery Services
Seafood Markets
Chicken Wings
Custom Cakes
Tex-Mex
Tacos
Middle Eastern
Greek
Lebanese
Nail Salons
Golf
Venues & Event Spaces
Active Life
Tennis
Arts & Entertainment
Country Clubs
Hotels & Travel
Bed & Breakfast
Cocktail Bars
Brasseries
Beer Gardens
Music Venues
Tapas/Small Plates
Arabic
Halal
Fruits & Veggies
Cajun/Creole
Candy Stores
Chocolatiers & Shops
Ramen
Pizza
Public Transportation
Transportation
Train Stations
Public Services & Government
Shopping
Hobby Shops
Gemstones & Minerals
Jewelry
Local Services
Psychics
Arts & Crafts
Watch Repair
Art Supplies
Flowers & Gifts
Gift Shops
Spiritual Shop
Astrologers
Supernatural Readings
Landmarks & Historical Buildings
Home & Garden
Toy Stores
Kitchen Supplies
Kitchen & Bath
Hotels
Cinema
Tires
Automotive
Auto Parts & Supplies
Auto Repair
Oil Change Stations
Professional Services
Airports
Drugstores
Pharmacy
Health & Medical
Aquariums
Tours
Zoos
Fashion
Leather Goods
Accessories
Bookstores
Books
Mags
Music & Video
Mobile Phones
Mobile Phone Accessories
Television Service Providers
Home Services
Museums
Creperies
Community Service/Non-Profit
Southern
Car Rental
Florists
Parks
Hungarian
Hot Pot
Public Markets
Farmers Market
Shaved Ice
Taiwanese
Massage Therapy
Reflexology
Live/Raw Food
Wine Bars
Cheesesteaks
Art Museums
Jazz & Blues
Art Galleries
Amusement Parks
Performing Arts
Shopping Centers
Massage
Used
Vintage & Consignment
Thrift Stores
Sports Bars
Spanish
Tapas Bars
Iberian
Kosher
Street Vendors
Cheese Shops
Latin American
Laotian
Caribbean
Chicken Shop
Hookah Bars
Dance Clubs
Venezuelan
International Grocery
Meat Shops
Women's Clothing
Dry Cleaning & Laundry
Laundry Services
Hair Salons
Pets
Pet Groomers
Pet Services
Pet Stores
Pet Training
Beer Bar
Bagels
Salvadoran
Honduran
Laser Tag
Bowling
Party & Event Planning
Discount Store
Department Stores
Malaysian
Electronics
Wholesale Stores
Bridal
Apartments
Real Estate
Peruvian
Modern European
Turkish
Irish
Gas Stations
Men's Clothing
Cosmetics & Beauty Supply
Wraps
Hawaiian
Poke
Brazilian
Gelato
Irish Pub
Used Car Dealers
Car Dealers
Body Shops
Persian/Iranian
Kebab
Donuts
Health Markets
Organic Stores
Cupcakes
Indonesian
Singaporean
Imported Food
Delicatessen
Barbers
Men's Hair Salons
Hair Stylists
Basque
Fondue
Pan Asian
Veterinarians
Pet Adoption
Cooking Classes
Ophthalmologists
Eyewear & Opticians
Doctors
Optometrists
Pasta Shops
Soul Food
Cuban
Outlet Stores
Herbs & Spices
Moroccan
Breweries
Falafel
Wineries
Cannabis Clinics
Personal Chefs
Argentine
Brewpubs
Nurseries & Gardening
Furniture Stores
Home Decor
Outdoor Furniture Stores
Tiki Bars
Coffee Roasteries
Conveyor Belt Sushi
Mongolian
Internet Cafes
Eyelash Service
Cosmetic Dentists
Pediatric Dentists
Orthodontists
Dentists
Auto Glass Services
Wedding Planning
Photography Stores & Services
Sports Wear
Outdoor Gear
Sporting Goods
Shoe Stores
Pretzels
Religious Organizations
Funeral Services & Cemeteries
Towing
Smog Check Stations
Filipino
Water Parks
Arcades
Hardware Stores
Building Supplies
Appliances
Appliances & Repair
Botanical Gardens
IT Services & Computer Repair
Computers
Education
Playgrounds
Kids Activities
Blow Dry/Out Services
Hair Extensions
Makeup Artists
Summer Camps
Swimming Pools
Izakaya
Recreation Centers
Axe Throwing
Stadiums & Arenas
Cultural Center
Empanadas
Acai Bowls
Waffles
General Dentistry
Comedy Clubs
Contractors
Food Court
Party Supplies
Festivals
Bike Repair/Maintenance
Bike Rentals
Bikes
Gyms
Interval Training Gyms
Trainers
Fitness & Instruction
Threading Services
Leisure Centers
Trampoline Parks
Ticket Sales
Laser Hair Removal
Medical Spas
Body Contouring
Unofficial Yelp Events
Specialty Schools
Brewing Supplies
Property Management
Real Estate Services
Real Estate Agents
Boot Camps
Macarons
Karaoke
Costumes
Newspapers & Magazines
Hiking
Gay Bars
Dance Studios
Dance Schools
Yoga
Sports Clubs
Knitting Supplies
Art Classes
Uzbek
Russian
Portuguese
Libraries
Patisserie/Cake Shop
Fish & Chips
Dominican
Burmese
Prenatal/Perinatal Care
Nutritionists
Parking
Casinos
Horse Racing
Watches
Antiques
Dive Bars
Spray Tanning
Tanning
Grout Services
Home Cleaning
Carpet Cleaning
Office Cleaning
Tiling
Air Duct Cleaning
Internet Service Providers
Tattoo Removal
Dermatologists
Cosmetic Surgeons
Yelp Events
Pet Boarding
Dog Walkers
Pet Sitting
Hats
Medical Centers
Physical Therapy
Sports Medicine
Shoe Repair
Sewing & Alterations
Shoe Shine
Formal Wear
Skating Rinks
Oral Surgeons
British
Perfume
African
Barre Classes
Distilleries
Tasting Classes
Cooking Schools
International
Acupuncture
Souvenir Shops
Office Equipment
Mattresses
Interior Design
Lighting Fixtures & Equipment
Professional Sports Teams
Adult Education
University Housing
Colleges & Universities
Mass Media
Radio Stations
Children's Museums
Keys & Locksmiths
Buses
Art Schools
Pilates
Martial Arts
Do-It-Yourself Food
Bar Crawl
Financial Services
Banks & Credit Unions
Hotel bar
Children's Clothing
Bistros
Oriental
Airport Shuttles
Mailbox Centers
Notaries
Laundromat
Couriers & Delivery Services
Shipping Centers
Signmaking
Printing Services
Personal Assistants
Dry Cleaning
Personal Shopping
Baseball Fields
Child Care & Day Care
Post Offices
Butcher
Telecommunications
Speakeasies
Eyebrow Services
Gardeners
Kombucha
Taxis
Musical Instruments & Teachers
Shaved Snow
New Mexican Cuisine
Colombian
Bounce House Rentals
Party Equipment Rentals
Hospitals
Emergency Rooms
Rugs
Baby Gear & Furniture
Indoor Playcentre
Airlines
Rafting/Kayaking
Electricians
Plumbing
Heating & Air Conditioning/HVAC
Dog Parks
Auto Detailing
Car Wash
Gold Buyers
Jewelry Repair
Beaches
Mini Golf
Maternity Wear
Cards & Stationery
Puerto Rican
Smokehouse
Halotherapy
Boating
Fishing
Shared Office Spaces
Mobile Phone Repair
Battery Stores
Electronics Repair
Wine Tasting Room
Nail Technicians
Olive Oil
Attraction Farms
Farms
Flea Markets
Water Heater Installation/Repair
Day Camps
Elementary Schools
Bespoke Clothing
Painters
Wheel & Rim Repair
Family Practice
Gastroenterologist
Pulmonologist
Sicilian
Estate Liquidation
Ethnic Grocery
Food Banks
Parenting Classes
Homeless Shelters
Auto Loan Providers
Pumpkin Patches
Christmas Trees
Surfing
Swimwear
Landscaping
Candle Stores
Scandinavian
Haunted Houses
Golf Equipment
Ziplining
Challenge Courses
Orthopedists
Windows Installation
Door Sales/Installation
Glass & Mirrors
Auto Customization
Window Washing
Home Window Tinting
Car Window Tinting
Homeowner Association
Paddleboarding
Boat Charters
Sunglasses
Austrian
Knife Sharpening
Tree Services
Cannabis Dispensaries
Vape Shops
Tobacco Shops
Vitamins & Supplements
Head Shops
Transmission Repair
Walk-in Clinics
Medical Supplies
Diagnostic Services
Laboratory Testing
Fabric Stores
Embroidery & Crochet
Used Bookstore
Permanent Makeup
Mortgage Brokers
Music & DVDs
Investing
Emergency Pet Hospital
Art Space Rentals
Hearing Aid Providers
Audiologist
Laser Eye Surgery/Lasik
Wigs
Osteopathic Physicians
Spine Surgeons
Podiatrists
Hostels
Resorts
Fitness/Exercise Equipment
Airport Terminals
Gun/Rifle Ranges
Hot Tub & Pool
Pool & Hot Tub Service
Pool Cleaners
Herbal Shops
Urgent Care
Dinner Theater
Animal Shelters
Team Building Activities
Escape Games
Marinas
Educational Services
Internal Medicine
Graphic Design
Limos
Plus Size Fashion
Service Stations
Lingerie
Pool Halls
Taxidermy
Screen Printing/T-Shirt Printing
Real Estate Photography
Photographers
Session Photography
Event Photography
Weight Loss Centers
Reproductive Health Services
Hair Loss Centers
Diagnostic Imaging
Adult
Endodontists
Cafeteria
Framing
Medical Cannabis Referrals
Guns & Ammo
Boat Tours
Surf Shop
Paint-Your-Own Pottery
Pet Insurance
Pet Cremation Services
Eatertainment
Climbing
Hunting & Fishing Supplies
Car Stereo Installation
Farming Equipment
Floral Designers
Home Organization
Virtual Reality Centers
Comic Books
Pediatricians
Architects
Swimming Lessons/Schools
Osteopaths
Lawn Services
Artificial Turf
Circuit Training Gyms
Preschools
Paint & Sip
Popcorn Shops
Auction Houses
Radiologists
Pawn Shops
Magicians
Pressure Washers
Refinishing Services
Holiday Decorations
Aerial Tours
Skydiving
Flight Instruction
Hang Gliding
Courthouses
Chiropractors
Pain Management
Adult Entertainment
Champagne Bars
Cigar Bars
Wholesalers
Restaurant Supplies
Damage Restoration
Life Insurance
Auto Insurance
Insurance
Home & Rental Insurance
Tattoo
Counseling & Mental Health
Vinyl Records
Race Tracks
Marketing
Advertising
Teppanyaki
Recycling Center
Lawyers
Videos & Video Game Rental
Flooring
Pest Control
Home Inspectors
Pool & Billiards
Departments of Motor Vehicles
Drive-Thru Bars
Social Clubs
Cideries
Meaderies
Movers
Packing Supplies
Truck Rental
Self Storage
Party Bus Rentals
Appraisal Services
Community Centers
Beverage Store
Donation Center
Ear Nose & Throat
Guitar Stores
Musical Instrument Services
Home Theatre Installation
Video Game Stores
Tabletop Games
Irrigation
Neurologist
RV Repair
Tax Services
ND
Septic Services
Aestheticians
Plastic Surgeons
Hypnosis/Hypnotherapy
Life Coach
Reiki
Psychic Mediums
Egyptian
Armenian
Wine Tours
Shades & Blinds
Shutters
Canadian (New)
Tanning Beds
Rehabilitation Center
Bartenders
Propane
Security Systems
Afghan
Local Fish Stores
Aquarium Services
Reptile Shops
Balloon Services
Roadside Assistance
Travel Services
Garage Door Services
Handyman
Kids Hair Salons
Party Bike Rentals
Rock Climbing
Japanese Curry
Web Design
Home Network Installation
Legal Services
Walking Tours
Piano Bars
Skate Parks
Races & Competitions
Pop-Up Restaurants
Piercing
Cycling Classes
Recording & Rehearsal Studios
Wedding Chapels
Obstetricians & Gynecologists
Churches
Tui Na
Traditional Chinese Medicine
Food Tours
Furniture Assembly
Cardio Classes
Home Automation
Historical Tours
Art Consultants
Commissioned Artists
Car Share Services
Pop-up Shops
Bike tours
Themed Cafes
Senegalese
Guest Houses
Amateur Sports Teams
Periodontists
Polish
DJs
Scottish
Language Schools
Photo Booth Rentals
Strip Clubs
Windshield Installation & Repair
Mountain Biking
Print Media
Carpeting
Batting Cages
Surgeons
Endocrinologists
Fertility
Data Recovery
Syrian
Uniforms
Auto Upholstery
Ukrainian
South African
Donairs
Poutineries
Hockey Equipment
Horse Boarding
Public Art
Lighting Stores
Coffee & Tea Supplies
Passport & Visa Services
Flowers
Television Stations
Customized Merchandise
Wine Tasting Classes
First Aid Classes
CPR Classes
Naturopathic/Holistic
Lakes
Gymnastics
Dental Hygienists
Music Production Services
Meditation Centers
Ski Resorts
Skiing
Ultrasound Imaging Centers
Water Purification Services
LAN Centers
Registration Services
Skate Shops
Architectural Tours
Car Buyers
Bicycle Paths
Video/Film Production
Estheticians
Float Spa
Cosmetology Schools
Soccer
Screen Printing
Pick Your Own Farms
Himalayan/Nepalese
Landscape Architects
Accountants
Wildlife Control
Skilled Nursing
Hospice
Home Health Care
Assisted Living Facilities
Retirement Homes
Planetarium
Observatories
Aerial Fitness
Basketball Courts
Tubing
Business Consulting
Paint Stores
Acne Treatment
Bird Shops
Shredding Services
Cardiologists
Go Karts
Occupational Therapy
Golf Lessons
Motorcycle Dealers
Drywall Installation & Repair
Pancakes
Orthotics
Disc Golf
Eastern European
Junkyards
High Fidelity Audio Equipment
Bankruptcy Law
Self-defense Classes
Firearm Training
Gunsmith
Coffeeshops
Livestock Feed & Supply
Art Tours
Vacation Rentals
Boat Dealers
RV Dealers
RV Rental
Luggage
Kickboxing
Vehicle Wraps
Health Retreats
Alternative Medicine
Boxing
Tuscan
Cabinetry
Pet Photography
Religious Items
Health Insurance Offices
Elevator Services
Junk Removal & Hauling
Packing Services
Sugaring
Fireplace Services
Roof Inspectors
Environmental Testing
Stucco Services
Tai Chi
Special Education
Pole Dancing Classes
Face Painting
Safety Equipment
Petting Zoos
Commercial Truck Dealers
Carpenters
Gutter Services
TV Mounting
Motorcycle Repair
Motorcycle Gear
Mobile Dent Repair
Archery
Vocational & Technical School
Nursing Schools
Cabaret
Aircraft Dealers
Private Jet Charter
Aircraft Repairs
Carpet Installation
Furniture Reupholstery
Boat Repair
Waterproofing
Trade Fairs
Airport Lounges
Commercial Truck Repair
Haitian
Trailer Rental
Racing Experience
Demolition Services
Campgrounds
RV Parks
Chimney Sweeps
Masonry/Concrete
Blood & Plasma Donation Centers
Trailer Dealers
Municipality
Home Staging
Divorce & Family Law
DUI Law
Criminal Defense Law
Personal Injury Law
Horseback Riding
Sailing
Holistic Animal Care
Pet Hospice
Siding
3D Printing
Makerspaces
CSA
Visitor Centers
Talent Agencies
Financial Advising
Clothing Rental
Countertop Installation
Condominiums
Indoor Landscaping
Bus Tours
Midwives
Boudoir Photography
Dance Wear
Car Inspectors
Pathologists
Sports Betting
Musicians
Metal Fabricators
Cremation Services
Chinese Martial Arts
Beer Tours
Somali
Middle Schools & High Schools
Furniture Repair
Trophy Shops
Hindu Temples
Synagogues
Valet Services
Ethical Grocery
Trains
Cannabis Collective
Kitchen Incubators
Rest Stops
Hazardous Waste Disposal
Utilities
Oncologist
Tutoring Centers
Trailer Repair
Mobility Equipment Sales & Services
Australian
Commercial Real Estate
Ayurveda
Roofing
Motorsport Vehicle Dealers
Grilling Equipment
Undersea/Hyperbaric Medicine
Health Coach
Oxygen Bars
Whale Watching Tours
Karate
Auto Security
Teacher Supplies
Psychiatrists
Urologists
Snow Removal
Decks & Railing
Carousels
Allergists
Opera & Ballet
Art Installation
Ski & Snowboard Shops
Insulation Installation
Massage Schools
Saunas
Henna Artists
Teeth Whitening
Jet Skis
Parasailing
IV Hydration
Driving Schools
Bangladeshi
Car Brokers
Piano Services
Engraving
Tableware
Wills
Trusts
& Probates
Real Estate Law
General Litigation
Estate Planning Law
Private Investigation
Security Services
Process Servers
Cryotherapy
Medical Transportation
Patio Coverings
Awnings
Hydro-jetting
Town Car Service
Employment Agencies
Travel Agents
Art Restoration
Paintball
Honey
Doulas
Police Departments
Ranches
Scuba Diving
Diving
Hakka
Officiants
Solar Installation
Hydroponics
Country Dance Halls
Pet Waste Removal
Anesthesiologists
Mortgage Lenders
Trinidadian
Sleep Specialists
Cheerleading
Retina Specialists
Vascular Medicine
Traditional Clothing
Bartending Schools
Beach Equipment Rentals
Scavenger Hunts
Business Law
College Counseling
Religious Schools
Fences & Gates
Bail Bondsmen
Childbirth Education
Flyboarding
Motorcycle Rental
Motorsport Vehicle Repairs
Dive Shops
Lactation Services
Photography Classes
Clock Repair
Nanny Services
Powder Coating
Prosthetics
Safe Stores
Glass Blowing
Dietitians
Water Stores
Drive-In Theater
Military Surplus
Fingerprinting
Sport Equipment Hire
Wallpapering
Rheumatologists
Vermouth Bars
Excavation Services
Nicaraguan
Check Cashing/Pay-day Loans
Farm Equipment Repair
Outdoor Power Equipment Services
Brazilian Jiu-jitsu
Lahmacun
Translation Services
Prosthodontists
Colonics
Audio/Visual Equipment Rental
Videographers
Club Crawl
Career Counseling
Furniture Rental
DIY Auto Shop
Bookkeepers
Test Preparation
Drones
Sledding
Nurse Practitioner
Concierge Medicine
Billing Services
Water Delivery
Title Loans
ATV Rentals/Tours
Sri Lankan
Backflow Services
Hospitalists
Payroll Services
Hydrotherapy
Machine & Tool Rental
Well Drilling
Addiction Medicine
Muay Thai
Silent Disco
Snorkeling
Personal Care Services
Fire Protection Services
Pedicabs
Ice Delivery
Nephrologists
Props
Parent Cafes
Beach Bars
Montessori Schools
Private Schools
Hybrid Car Repair
Horse Equipment Shops
Dumpster Rental
Pet Transportation
Private Tutors
Dumplings
Fireworks
Veterans Organizations
Adoption Services
Employment Law
Workers Compensation Law
Medical Law
Sports Psychologists
Animal Physical Therapy
Installment Loans
Sex Therapists
Golf Equipment Shops
Rolfing
Debt Relief Services
Pet Breeders
Electricity Suppliers
Buddhist Temples
Community Gardens
Holiday Decorating Services
Home Developers
Environmental Abatement
Psychologists
Behavior Analysts
Czech
Piano Stores
Dart Arenas
Airsoft
Public Relations
Party Characters
Software Development
Calligraphy
EV Charging Stations
Neuropathologists
Traffic Ticketing Law
Ferries
Matchmakers
Trivia Hosts
Badminton
Lice Services
Machine Shops
Speech Therapists
Motorcycle Parts & Supplies
Immigration Law
Currency Exchange
Vocal Coach
Playsets
Memory Care
Waldorf Schools
Striptease Dancers
Duplication Services
Spin Classes
Sauna Installation & Repair
Surf Schools
Scooter Tours
Mortuary Services
Caricatures
Public Adjusters
Preventive Medicine
Land Surveying
Structural Engineers
Firewood
Golf Cart Rentals
House Sitters
Sardinian
Georgian
Bingo Halls
Boat Parts & Supplies
Cannabis Tours
Mediators
Ceremonial Clothing
Bike Sharing
Diamond Buyers
IP & Internet Law
Senior Centers
Qi Gong
Digitizing Services
Hot Air Balloons
Car Auctions
Fuzhou
Nudist
Mobile Home Dealers
Generator Installation/Repair
Taekwondo
Animal Assisted Therapy
Fur Clothing
Vehicle Shipping
Apartment Agents
Clowns
Luggage Storage
Social Security Law
Free Diving
Vacation Rental Agents
Mobile Home Parks
Infectious Disease Specialists
Immunodermatologists
Emergency Medicine
Editorial Services
Jails & Prisons
Proctologists
Bus Stations
Gerontologists
Disability Law
Tax Law
Sheds & Outdoor Storage
Business Financing

Una vez desanidada la informacion, se filtran por aquellos que son de nuestro interés

In [24]:
# Mencionamos aquellos negocios en los que vamos a trabajar
keywords = ['Museum', 'Park', 'Hotel', 'Motel', 'Hostel', 'Restaurant', 'Restaurant', 'Forest', 'Gallery', 'Mall', 'Pub', 'Zoo', 'Roller Coaster']

# Crear una máscara booleana para filtrar las filas
mask = rt_df['categories'].str.contains('|'.join(keywords))

# Aplicar la máscara para conservar solo las filas que contienen las palabras clave
filtered_dataframe = rt_df[mask]

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 26, Finished, Available)

De esta forma nos queda un dataframe filtrado solo con la informacion que nos interesa

In [25]:
filtered_dataframe

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 27, Finished, Available)

,business_id,name_x,address,city,state,latitude,longitude,stars_x,review_count,categories,count_checkin,user_id,stars_y,text,date,name_y
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,Restaurants,335,6_SpY41LIHZuIaiDs5FMKA,4,This is nice little Chinese bakery in the hear...,2014-05-26 01:09:53,K
1,i_sAh-ylmOwCQmqRmXox8g,Monsú,901 Christian St,Philadelphia,IN,39.939138,-75.157907,4.0,309,Restaurants,292,6_SpY41LIHZuIaiDs5FMKA,2,Had a mediocre late-lunch here on a Saturday a...,2014-12-04 07:03:34,K
2,9Qe5ib0bCgRITjYn-iA-Bg,Legal Sea Foods,8500 Essington Ave,Philadelphia,FL,39.876009,-75.242965,4.0,326,Restaurants,1335,6_SpY41LIHZuIaiDs5FMKA,2,Among the different Legal Sea Foods restaurant...,2014-12-04 07:12:51,K
4,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,Restaurants,335,tCXElwhzekJEH6QJe3xs7Q,4,This is the bakery I usually go to in Chinatow...,2013-10-05 15:19:06,Rob
5,EtKSTHV5Qx_Q7Aur9o4kQQ,Village Whiskey,118 S 20th St,Philadelphia,CA,39.951417,-75.173768,4.0,1553,Restaurants,3128,tCXElwhzekJEH6QJe3xs7Q,5,....the best burger I've had in my life. Just...,2011-06-02 01:56:45,Rob
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2802859,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,Restaurants,64,Jude3QtCq1_-47DU5aRgpw,3,There's only one reason this isn't a 5 star lo...,2017-05-05 16:07:15,RyeRye
2802860,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,Restaurants,64,V6D36_zHFs_GYTx8b9Bojg,5,Had a craving for a good hoagie and ended up h...,2014-05-01 01:40:36,Umaar
2802861,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,Restaurants,64,vknXDPuG77v-ei7YuiDr9g,1,Awful. I place an order for delivery via their...,2020-06-25 16:23:55,Michael
2802862,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,Restaurants,64,LoS__jrtFOBWy6DZ-ZdZBg,1,I ordered from Ridge ave./ Roxboro location tw...,2021-06-01 20:12:06,Mark
2802863,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,Restaurants,64,rNMb41ZjOT-YFiiIYIgF7w,1,Would give 0 stars if possible. Hoagies were a...,2021-09-04 02:20:00,Lydia

 Ahora procedemos a anidar nuevamente las categorias usando la funcion group_column

In [26]:
##agrupar nuevamente las categorias y el resto de la información
filtered_dataframe = ut.group_column(filtered_dataframe, 'categories')
filtered_dataframe

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 28, Finished, Available)

,business_id,name_x,address,city,state,latitude,longitude,stars_x,review_count,count_checkin,user_id,stars_y,text,date,name_y,categories
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,335,6_SpY41LIHZuIaiDs5FMKA,4,This is nice little Chinese bakery in the hear...,2014-05-26 01:09:53,K,[Restaurants]
1,i_sAh-ylmOwCQmqRmXox8g,Monsú,901 Christian St,Philadelphia,IN,39.939138,-75.157907,4.0,309,292,6_SpY41LIHZuIaiDs5FMKA,2,Had a mediocre late-lunch here on a Saturday a...,2014-12-04 07:03:34,K,[Restaurants]
2,9Qe5ib0bCgRITjYn-iA-Bg,Legal Sea Foods,8500 Essington Ave,Philadelphia,FL,39.876009,-75.242965,4.0,326,1335,6_SpY41LIHZuIaiDs5FMKA,2,Among the different Legal Sea Foods restaurant...,2014-12-04 07:12:51,K,[Restaurants]
4,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,335,tCXElwhzekJEH6QJe3xs7Q,4,This is the bakery I usually go to in Chinatow...,2013-10-05 15:19:06,Rob,[Restaurants]
5,EtKSTHV5Qx_Q7Aur9o4kQQ,Village Whiskey,118 S 20th St,Philadelphia,CA,39.951417,-75.173768,4.0,1553,3128,tCXElwhzekJEH6QJe3xs7Q,5,....the best burger I've had in my life. Just...,2011-06-02 01:56:45,Rob,[Restaurants]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2802859,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,64,Jude3QtCq1_-47DU5aRgpw,3,There's only one reason this isn't a 5 star lo...,2017-05-05 16:07:15,RyeRye,[Restaurants]
2802860,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,64,V6D36_zHFs_GYTx8b9Bojg,5,Had a craving for a good hoagie and ended up h...,2014-05-01 01:40:36,Umaar,[Restaurants]
2802861,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,64,vknXDPuG77v-ei7YuiDr9g,1,Awful. I place an order for delivery via their...,2020-06-25 16:23:55,Michael,[Restaurants]
2802862,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,64,LoS__jrtFOBWy6DZ-ZdZBg,1,I ordered from Ridge ave./ Roxboro location tw...,2021-06-01 20:12:06,Mark,[Restaurants]
2802863,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,64,rNMb41ZjOT-YFiiIYIgF7w,1,Would give 0 stars if possible. Hoagies were a...,2021-09-04 02:20:00,Lydia,[Restaurants]

In [27]:
ut.data_summ(filtered_dataframe)

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 29, Finished, Available)

       Column                                            Data_type  No_miss_Qty  %Missing  Missing_Qty
  business_id                                      [<class 'str'>]      2093415       0.0            0
       name_x                                      [<class 'str'>]      2093415       0.0            0
      address                                      [<class 'str'>]      2093415       0.0            0
         city                                      [<class 'str'>]      2093415       0.0            0
        state                                      [<class 'str'>]      2093415       0.0            0
     latitude                                    [<class 'float'>]      2093415       0.0            0
    longitude                                    [<class 'float'>]      2093415       0.0            0
      stars_x                                    [<class 'float'>]      2093415       0.0            0
 review_count                                      [<class 'int'>]      2093415       0.0            0
count_checkin                                      [<class 'int'>]      2093415       0.0            0
      user_id                                      [<class 'str'>]      2093415       0.0            0
      stars_y                                      [<class 'int'>]      2093415       0.0            0
         text                                      [<class 'str'>]      2093415       0.0            0
         date [<class 'pandas._libs.tslibs.timestamps.Timestamp'>]      2093415       0.0            0
       name_y                                      [<class 'str'>]      2093415       0.0            0
   categories                                     [<class 'list'>]      2093415       0.0            0
=====================================

,Column,Data_type,No_miss_Qty,%Missing,Missing_Qty
0,business_id,[<class 'str'>],2093415,0.0,0
1,name_x,[<class 'str'>],2093415,0.0,0
2,address,[<class 'str'>],2093415,0.0,0
3,city,[<class 'str'>],2093415,0.0,0
4,state,[<class 'str'>],2093415,0.0,0
5,latitude,[<class 'float'>],2093415,0.0,0
6,longitude,[<class 'float'>],2093415,0.0,0
7,stars_x,[<class 'float'>],2093415,0.0,0
8,review_count,[<class 'int'>],2093415,0.0,0
9,count_checkin,[<class 'int'>],2093415,0.0,0
10,user_id,[<class 'str'>],2093415,0.0,0
11,stars_y,[<class 'int'>],2093415,0.0,0
12,text,[<class 'str'>],2093415,0.0,0
13,date,[<class 'pandas._libs.tslibs.timestamps.Timest...,2093415,0.0,0
14,name_y,[<class 'str'>],2093415,0.0,0
15,categories,[<class 'list'>],2093415,0.0,0

In [28]:
Yelp = filtered_dataframe[["name_x", "address", "city", "state", "latitude", "longitude", "stars_x", "review_count", "date", "count_checkin", "user_id", "stars_y", "text", "name_y", "categories"]]

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 30, Finished, Available)

In [29]:
Yelp = Yelp.rename(columns={
    "name_x": 'Business_Name',
    "address": 'Address',
    "city": 'City',
    "state": 'State',
    "latitude": 'Latitude',
    "longitude": 'Longitude',
    "stars_x": 'Ranking',
    "review_count": 'Review_Count',
    "date" : "Date",
    "count_checkin": 'Checkin_Count',
    "user_id": 'User_Id',
    "stars_y": 'Stars',
    "text": 'Text',
    "name_y": 'User_Name',
    "categories": 'Category'
})

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 31, Finished, Available)

Una vez filtrado el Dataframe y reagrupado, terminamos generando un archivo parquet el cual contiene toda la informacion filtrada separada en las columnas:
- 'Business_Name',
- 'Address',
- 'City',
- 'State',
- 'Latitude',
- 'Longitude',
- 'Ranking',
- 'Review_Count',
- 'Checkin_Count',
- 'User_Id',
- 'Stars',
- 'Text',
- 'User_Name',
- 'Category’

In [30]:
Yelp

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 32, Finished, Available)

,Business_Name,Address,City,State,Latitude,Longitude,Ranking,Review_Count,Date,Checkin_Count,User_Id,Stars,Text,User_Name,Category
0,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,2014-05-26 01:09:53,335,6_SpY41LIHZuIaiDs5FMKA,4,This is nice little Chinese bakery in the hear...,K,[Restaurants]
1,Monsú,901 Christian St,Philadelphia,IN,39.939138,-75.157907,4.0,309,2014-12-04 07:03:34,292,6_SpY41LIHZuIaiDs5FMKA,2,Had a mediocre late-lunch here on a Saturday a...,K,[Restaurants]
2,Legal Sea Foods,8500 Essington Ave,Philadelphia,FL,39.876009,-75.242965,4.0,326,2014-12-04 07:12:51,1335,6_SpY41LIHZuIaiDs5FMKA,2,Among the different Legal Sea Foods restaurant...,K,[Restaurants]
4,St Honore Pastries,935 Race St,Philadelphia,CA,39.955505,-75.155564,4.0,80,2013-10-05 15:19:06,335,tCXElwhzekJEH6QJe3xs7Q,4,This is the bakery I usually go to in Chinatow...,Rob,[Restaurants]
5,Village Whiskey,118 S 20th St,Philadelphia,CA,39.951417,-75.173768,4.0,1553,2011-06-02 01:56:45,3128,tCXElwhzekJEH6QJe3xs7Q,5,....the best burger I've had in my life. Just...,Rob,[Restaurants]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2802859,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,2017-05-05 16:07:15,64,Jude3QtCq1_-47DU5aRgpw,3,There's only one reason this isn't a 5 star lo...,RyeRye,[Restaurants]
2802860,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,2014-05-01 01:40:36,64,V6D36_zHFs_GYTx8b9Bojg,5,Had a craving for a good hoagie and ended up h...,Umaar,[Restaurants]
2802861,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,2020-06-25 16:23:55,64,vknXDPuG77v-ei7YuiDr9g,1,Awful. I place an order for delivery via their...,Michael,[Restaurants]
2802862,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,2021-06-01 20:12:06,64,LoS__jrtFOBWy6DZ-ZdZBg,1,I ordered from Ridge ave./ Roxboro location tw...,Mark,[Restaurants]
2802863,PrimoHoagies,6024 Ridge Ave,Philadelphia,CA,40.032483,-75.214430,3.0,55,2021-09-04 02:20:00,64,rNMb41ZjOT-YFiiIYIgF7w,1,Would give 0 stars if possible. Hoagies were a...,Lydia,[Restaurants]

In [31]:
Yelp.to_parquet('/lakehouse/default/Files/df_database/files_to_EDA/Yelp_to_EDA.parquet')

StatementMeta(, a3187e28-f8e2-4118-8fc9-9033074eaf5f, 33, Finished, Available)